In [ ]:
# ============================================================
# M3 ROUTE AGENT v2
# STEP 1: LOAD ROUTING DATASET
# ============================================================

import pandas as pd
import numpy as np
import json

FILE_PATH = "unified_routing 2.csv"

route_df = pd.read_csv(FILE_PATH)

print("Route dataset loaded successfully!")
print("=" * 60)

print("Dataset shape:", route_df.shape)

print("\nColumns:")
for i, col in enumerate(route_df.columns, start=1):
    print(f"{i}. {col}")

print("\nFirst 5 rows:")
display(route_df.head())

Route dataset loaded successfully!
============================================================
Dataset shape: (2037, 23)

Columns:
1. zone_id
2. region
3. latitude
4. longitude
5. pfz_distance_km
6. pfz_depth_m
7. water_depth_m
8. current_u_ms
9. current_v_ms
10. current_speed_ms
11. eez_boundary_distance_km
12. nearest_boundary_type
13. geofence_caution
14. inside_mpa
15. mpa_distance_km
16. mpa_caution
17. distance_km
18. travel_time_hr
19. fuel_l_proxy
20. route_score
21. routing_class
22. agent
23. data_region

First 5 rows:

,zone_id,region,latitude,longitude,pfz_distance_km,pfz_depth_m,water_depth_m,current_u_ms,current_v_ms,current_speed_ms,...,inside_mpa,mpa_distance_km,mpa_caution,distance_km,travel_time_hr,fuel_l_proxy,route_score,routing_class,agent,data_region
0,PFZ0001,ANDAMAN,13.170278,92.640278,20.0,15.0,20.0,NaN,NaN,NaN,...,0,1053.068365,0,20.0,1.111111,8.888889,NaN,NaN,ROUTE_AGENT,BROADER_INDIAN_MARINE_REGION
1,PFZ0002,ANDAMAN,11.760000,92.946944,16.0,97.0,102.0,NaN,NaN,NaN,...,0,1213.398008,0,16.0,0.888889,7.111111,NaN,NaN,ROUTE_AGENT,BROADER_INDIAN_MARINE_REGION
2,PFZ0003,ANDAMAN,11.745000,93.004444,8.0,67.0,75.0,NaN,NaN,NaN,...,0,1215.136296,0,8.0,0.444444,3.555556,NaN,NaN,ROUTE_AGENT,BROADER_INDIAN_MARINE_REGION
3,PFZ0004,ANDAMAN,11.694444,93.021944,27.0,226.0,249.0,NaN,NaN,NaN,...,0,1220.900345,0,27.0,1.500000,12.000000,NaN,NaN,ROUTE_AGENT,BROADER_INDIAN_MARINE_REGION
4,PFZ0005,ANDAMAN,11.632500,93.021111,33.0,254.0,230.0,NaN,NaN,NaN,...,0,1227.940194,0,33.0,1.833333,14.666667,NaN,NaN,ROUTE_AGENT,BROADER_INDIAN_MARINE_REGION

In [ ]:
# ============================================================
# STEP 2: ROUTE FEATURE AVAILABILITY / MISSING DATA
# ============================================================

print("ROUTE FEATURE AVAILABILITY")
print("=" * 60)

# Routing variables used by M3
route_cols = [
    "distance_km",
    "travel_time_hr",
    "fuel_l_proxy",
    "water_depth_m",
    "current_u_ms",
    "current_v_ms",
    "current_speed_ms",
    "geofence_caution",
    "inside_mpa",
    "mpa_distance_km",
    "mpa_caution",
    "eez_boundary_distance_km"
]

# Keep only columns actually present
route_cols = [col for col in route_cols if col in route_df.columns]

# Missing values
print("\nMissing values in routing features:\n")
print(route_df[route_cols].isnull().sum())

# Availability
print("\nFeature availability:\n")

for col in route_cols:
    available = route_df[col].notna().sum()
    total = len(route_df)
    percentage = (available / total) * 100

    print(
        f"{col}: "
        f"{available}/{total} available "
        f"({percentage:.2f}%)"
    )

# Statistics
print("\nRouting feature statistics:\n")

display(
    route_df[route_cols]
    .describe()
    .T
)

ROUTE FEATURE AVAILABILITY
============================================================

Missing values in routing features:

distance_km                   0
travel_time_hr                0
fuel_l_proxy                  0
water_depth_m                 0
current_u_ms                495
current_v_ms                495
current_speed_ms            495
geofence_caution              0
inside_mpa                    0
mpa_distance_km               0
mpa_caution                   0
eez_boundary_distance_km      0
dtype: int64

Feature availability:

distance_km: 2037/2037 available (100.00%)
travel_time_hr: 2037/2037 available (100.00%)
fuel_l_proxy: 2037/2037 available (100.00%)
water_depth_m: 2037/2037 available (100.00%)
current_u_ms: 1542/2037 available (75.70%)
current_v_ms: 1542/2037 available (75.70%)
current_speed_ms: 1542/2037 available (75.70%)
geofence_caution: 2037/2037 available (100.00%)
inside_mpa: 2037/2037 available (100.00%)
mpa_distance_km: 2037/2037 available (100.00%)
mpa_caution: 2037/2037 available (100.00%)
eez_boundary_distance_km: 2037/2037 available (100.00%)

Routing feature statistics:

,count,mean,std,min,25%,50%,75%,max
distance_km,2037.0,218.027938,147.399515,1.455515,71.000000,210.456495,342.585106,499.526461
travel_time_hr,2037.0,12.112663,8.188862,0.080862,3.944444,11.692028,19.032506,27.751470
fuel_l_proxy,2037.0,96.901306,65.510896,0.646896,31.555556,93.536220,152.260047,222.011760
water_depth_m,2037.0,1521.349043,1504.664539,0.000000,29.000000,1267.000000,2922.000000,4886.000000
current_u_ms,1542.0,0.009893,0.125369,-0.390000,-0.060500,0.005250,0.071000,0.666000
current_v_ms,1542.0,0.029506,0.121110,-0.344500,-0.055250,0.017000,0.093875,0.553000
current_speed_ms,1542.0,0.145337,0.101081,0.003536,0.070866,0.122623,0.197116,0.730449
geofence_caution,2037.0,0.024546,0.154775,0.000000,0.000000,0.000000,0.000000,1.000000
inside_mpa,2037.0,0.002455,0.049495,0.000000,0.000000,0.000000,0.000000,1.000000
mpa_distance_km,2037.0,465.000241,423.560791,0.000000,118.646693,327.952229,670.263679,1768.844050
mpa_caution,2037.0,0.005400,0.073305,0.000000,0.000000,0.000000,0.000000,1.000000
eez_boundary_distance_km,2037.0,101.195432,93.649535,0.007937,36.218763,74.314149,133.067122,518.277390

In [ ]:
# ============================================================
# STEP 3: ROUTE FEATURE ENGINEERING
# ============================================================

# Keep original dataset unchanged
route_features_df = route_df.copy()

# ------------------------------------------------------------
# 1. Current direction from U and V components
# ------------------------------------------------------------

route_features_df["current_direction_deg"] = (
    np.degrees(
        np.arctan2(
            route_features_df["current_v_ms"],
            route_features_df["current_u_ms"]
        )
    ) + 360
) % 360


# ------------------------------------------------------------
# 2. Log transformation for fuel
# Helps reduce the influence of very large fuel values
# ------------------------------------------------------------

route_features_df["fuel_log"] = np.log1p(
    route_features_df["fuel_l_proxy"]
)


# ------------------------------------------------------------
# 3. Log transformation for travel time
# ------------------------------------------------------------

route_features_df["travel_time_log"] = np.log1p(
    route_features_df["travel_time_hr"]
)


# ------------------------------------------------------------
# 4. Route-data availability
# ------------------------------------------------------------

core_route_features = [
    "distance_km",
    "travel_time_hr",
    "fuel_l_proxy",
    "water_depth_m",
    "current_speed_ms"
]

route_features_df["route_features_available"] = (
    route_features_df[core_route_features]
    .notna()
    .sum(axis=1)
)

route_features_df["route_data_completeness"] = (
    route_features_df["route_features_available"]
    / len(core_route_features)
)


# ------------------------------------------------------------
# 5. Safety / constraint availability
# ------------------------------------------------------------

safety_features = [
    "water_depth_m",
    "geofence_caution",
    "inside_mpa",
    "mpa_distance_km",
    "mpa_caution",
    "eez_boundary_distance_km"
]

available_safety_features = [
    col for col in safety_features
    if col in route_features_df.columns
]

route_features_df["safety_features_available"] = (
    route_features_df[available_safety_features]
    .notna()
    .sum(axis=1)
)

route_features_df["safety_data_completeness"] = (
    route_features_df["safety_features_available"]
    / len(available_safety_features)
)


# ------------------------------------------------------------
# 6. Inspect engineered features
# ------------------------------------------------------------

engineered_route_features = [
    "zone_id",
    "region",
    "latitude",
    "longitude",
    "distance_km",
    "travel_time_hr",
    "fuel_l_proxy",
    "fuel_log",
    "travel_time_log",
    "water_depth_m",
    "current_u_ms",
    "current_v_ms",
    "current_speed_ms",
    "current_direction_deg",
    "route_features_available",
    "route_data_completeness",
    "safety_features_available",
    "safety_data_completeness"
]

print("✅ Route feature engineering completed!")
print("\nNew dataset shape:", route_features_df.shape)

print("\nEngineered route features:")
display(
    route_features_df[engineered_route_features].head(10)
)

✅ Route feature engineering completed!

New dataset shape: (2037, 30)

Engineered route features:

,zone_id,region,latitude,longitude,distance_km,travel_time_hr,fuel_l_proxy,fuel_log,travel_time_log,water_depth_m,current_u_ms,current_v_ms,current_speed_ms,current_direction_deg,route_features_available,route_data_completeness,safety_features_available,safety_data_completeness
0,PFZ0001,ANDAMAN,13.170278,92.640278,20.0,1.111111,8.888889,2.291412,0.747214,20.0,NaN,NaN,NaN,NaN,4,0.8,6,1.0
1,PFZ0002,ANDAMAN,11.760000,92.946944,16.0,0.888889,7.111111,2.093235,0.635989,102.0,NaN,NaN,NaN,NaN,4,0.8,6,1.0
2,PFZ0003,ANDAMAN,11.745000,93.004444,8.0,0.444444,3.555556,1.516347,0.367725,75.0,NaN,NaN,NaN,NaN,4,0.8,6,1.0
3,PFZ0004,ANDAMAN,11.694444,93.021944,27.0,1.500000,12.000000,2.564949,0.916291,249.0,NaN,NaN,NaN,NaN,4,0.8,6,1.0
4,PFZ0005,ANDAMAN,11.632500,93.021111,33.0,1.833333,14.666667,2.751535,1.041454,230.0,NaN,NaN,NaN,NaN,4,0.8,6,1.0
5,PFZ0006,ANDAMAN,11.587778,93.025833,34.0,1.888889,15.111111,2.779509,1.060872,453.0,-0.0295,0.0510,0.058917,120.046435,5,1.0,6,1.0
6,PFZ0007,ANDAMAN,11.563889,92.999444,29.0,1.611111,12.888889,2.631089,0.959776,499.0,-0.0295,0.0510,0.058917,120.046435,5,1.0,6,1.0
7,PFZ0008,ANDAMAN,11.535556,92.975556,30.0,1.666667,13.333333,2.662588,0.980829,468.0,-0.0295,0.0510,0.058917,120.046435,5,1.0,6,1.0
8,PFZ0009,ANDAMAN,11.501944,92.983889,27.0,1.500000,12.000000,2.564949,0.916291,601.0,-0.0295,0.0510,0.058917,120.046435,5,1.0,6,1.0
9,PFZ0010,ANDAMAN,11.362500,92.978333,45.0,2.500000,20.000000,3.044522,1.252763,1149.0,-0.0435,0.0555,0.070516,128.088774,5,1.0,6,1.0

In [ ]:
# ============================================================
# STEP 4: DATA-DRIVEN ROUTE REFERENCE PARAMETERS
# ============================================================

print("ROUTE REFERENCE PARAMETERS")
print("=" * 60)

# ------------------------------------------------------------
# Distance references
# Lower distance is better
# ------------------------------------------------------------

dist_q10 = route_features_df["distance_km"].quantile(0.10)
dist_q50 = route_features_df["distance_km"].quantile(0.50)
dist_q90 = route_features_df["distance_km"].quantile(0.90)


# ------------------------------------------------------------
# Travel-time references
# Lower travel time is better
# ------------------------------------------------------------

time_q10 = route_features_df["travel_time_hr"].quantile(0.10)
time_q50 = route_features_df["travel_time_hr"].quantile(0.50)
time_q90 = route_features_df["travel_time_hr"].quantile(0.90)


# ------------------------------------------------------------
# Fuel references
# Lower fuel requirement is better
# ------------------------------------------------------------

fuel_q10 = route_features_df["fuel_l_proxy"].quantile(0.10)
fuel_q50 = route_features_df["fuel_l_proxy"].quantile(0.50)
fuel_q90 = route_features_df["fuel_l_proxy"].quantile(0.90)


# ------------------------------------------------------------
# Water-depth references
# Kept as data-driven reference values for safety scoring
# ------------------------------------------------------------

depth_q10 = route_features_df["water_depth_m"].quantile(0.10)
depth_q50 = route_features_df["water_depth_m"].quantile(0.50)
depth_q90 = route_features_df["water_depth_m"].quantile(0.90)


# ------------------------------------------------------------
# MPA-distance references
# Larger distance from MPA is potentially safer
# ------------------------------------------------------------

mpa_q10 = route_features_df["mpa_distance_km"].quantile(0.10)
mpa_q50 = route_features_df["mpa_distance_km"].quantile(0.50)
mpa_q90 = route_features_df["mpa_distance_km"].quantile(0.90)


# ------------------------------------------------------------
# Current-speed references
# Kept for route-safety/current-related analysis
# ------------------------------------------------------------

current_q10 = route_features_df["current_speed_ms"].quantile(0.10)
current_q50 = route_features_df["current_speed_ms"].quantile(0.50)
current_q90 = route_features_df["current_speed_ms"].quantile(0.90)


# ------------------------------------------------------------
# Display reference parameters
# ------------------------------------------------------------

print("\nDistance:")
print(f"10th percentile : {dist_q10:.4f}")
print(f"Median          : {dist_q50:.4f}")
print(f"90th percentile : {dist_q90:.4f}")

print("\nTravel Time:")
print(f"10th percentile : {time_q10:.4f}")
print(f"Median          : {time_q50:.4f}")
print(f"90th percentile : {time_q90:.4f}")

print("\nFuel:")
print(f"10th percentile : {fuel_q10:.4f}")
print(f"Median          : {fuel_q50:.4f}")
print(f"90th percentile : {fuel_q90:.4f}")

print("\nWater Depth:")
print(f"10th percentile : {depth_q10:.4f}")
print(f"Median          : {depth_q50:.4f}")
print(f"90th percentile : {depth_q90:.4f}")

print("\nMPA Distance:")
print(f"10th percentile : {mpa_q10:.4f}")
print(f"Median          : {mpa_q50:.4f}")
print(f"90th percentile : {mpa_q90:.4f}")

print("\nCurrent Speed:")
print(f"10th percentile : {current_q10:.4f}")
print(f"Median          : {current_q50:.4f}")
print(f"90th percentile : {current_q90:.4f}")

ROUTE REFERENCE PARAMETERS
============================================================

Distance:
10th percentile : 33.0000
Median          : 210.4565
90th percentile : 428.0583

Travel Time:
10th percentile : 1.8333
Median          : 11.6920
90th percentile : 23.7810

Fuel:
10th percentile : 14.6667
Median          : 93.5362
90th percentile : 190.2481

Water Depth:
10th percentile : 0.0000
Median          : 1267.0000
90th percentile : 3580.0000

MPA Distance:
10th percentile : 70.1678
Median          : 327.9522
90th percentile : 1186.9220

Current Speed:
10th percentile : 0.0424
Median          : 0.1226
90th percentile : 0.2711

In [ ]:
# ============================================================
# STEP 5: DISTANCE SUITABILITY SCORE
# ============================================================

def distance_route_score(x):
    """
    Convert route distance into a 0-1 suitability score.

    Lower distance = better route suitability.
    """

    if pd.isna(x):
        return np.nan

    # Very short distances = maximum suitability
    if x <= dist_q10:
        return 1.0

    # Very long distances = minimum suitability
    if x >= dist_q90:
        return 0.0

    # Linear scaling between q10 and q90
    score = (
        (dist_q90 - x)
        / (dist_q90 - dist_q10)
    )

    return np.clip(score, 0, 1)


# Apply distance scoring
route_features_df["distance_score"] = (
    route_features_df["distance_km"]
    .apply(distance_route_score)
)


# ------------------------------------------------------------
# Inspect results
# ------------------------------------------------------------

print("✅ Distance suitability score calculated")

print("\nDistance score statistics:")
print(
    route_features_df["distance_score"]
    .describe()
)

print("\nSample distance scores:")

display(
    route_features_df[
        [
            "zone_id",
            "distance_km",
            "distance_score"
        ]
    ].head(15)
)

✅ Distance suitability score calculated

Distance score statistics:
count    2037.000000
mean        0.537399
std         0.355337
min         0.000000
25%         0.216356
50%         0.550809
75%         0.903812
max         1.000000
Name: distance_score, dtype: float64

Sample distance scores:

    zone_id  distance_km  distance_score
0   PFZ0001         20.0        1.000000
1   PFZ0002         16.0        1.000000
2   PFZ0003          8.0        1.000000
3   PFZ0004         27.0        1.000000
4   PFZ0005         33.0        1.000000
5   PFZ0006         34.0        0.997469
6   PFZ0007         29.0        1.000000
7   PFZ0008         30.0        1.000000
8   PFZ0009         27.0        1.000000
9   PFZ0010         45.0        0.969625
10  PFZ0011         33.0        1.000000
11  PFZ0012         18.0        1.000000
12  PFZ0013         27.0        1.000000
13  PFZ0014         13.0        1.000000
14  PFZ0015         17.0        1.000000

In [ ]:
# ============================================================
# STEP 6: TRAVEL-TIME SUITABILITY SCORE
# ============================================================

def travel_time_route_score(x):
    """
    Convert travel time into a 0-1 suitability score.

    Lower travel time = better route suitability.
    """

    if pd.isna(x):
        return np.nan

    # Very short travel time = maximum suitability
    if x <= time_q10:
        return 1.0

    # Very long travel time = minimum suitability
    if x >= time_q90:
        return 0.0

    # Linear inverse scaling between q10 and q90
    score = (
        (time_q90 - x)
        / (time_q90 - time_q10)
    )

    return np.clip(score, 0, 1)


# Apply travel-time scoring
route_features_df["travel_time_score"] = (
    route_features_df["travel_time_hr"]
    .apply(travel_time_route_score)
)


# ------------------------------------------------------------
# Inspect results
# ------------------------------------------------------------

print("✅ Travel-time suitability score calculated")

print("\nTravel-time score statistics:")
print(
    route_features_df["travel_time_score"]
    .describe()
)

print("\nSample travel-time scores:")

display(
    route_features_df[
        [
            "zone_id",
            "travel_time_hr",
            "travel_time_score"
        ]
    ].head(15)
)

✅ Travel-time suitability score calculated

Travel-time score statistics:
count    2037.000000
mean        0.537399
std         0.355337
min         0.000000
25%         0.216356
50%         0.550809
75%         0.903812
max         1.000000
Name: travel_time_score, dtype: float64

Sample travel-time scores:

    zone_id  travel_time_hr  travel_time_score
0   PFZ0001        1.111111           1.000000
1   PFZ0002        0.888889           1.000000
2   PFZ0003        0.444444           1.000000
3   PFZ0004        1.500000           1.000000
4   PFZ0005        1.833333           1.000000
5   PFZ0006        1.888889           0.997469
6   PFZ0007        1.611111           1.000000
7   PFZ0008        1.666667           1.000000
8   PFZ0009        1.500000           1.000000
9   PFZ0010        2.500000           0.969625
10  PFZ0011        1.833333           1.000000
11  PFZ0012        1.000000           1.000000
12  PFZ0013        1.500000           1.000000
13  PFZ0014        0.722222           1.000000
14  PFZ0015        0.944444           1.000000

In [ ]:
# ============================================================
# STEP 7: FUEL SUITABILITY SCORE
# ============================================================

def fuel_route_score(x):
    """
    Convert fuel requirement into a 0-1 suitability score.

    Lower fuel requirement = better route suitability.
    """

    if pd.isna(x):
        return np.nan

    # Very low fuel requirement = maximum suitability
    if x <= fuel_q10:
        return 1.0

    # Very high fuel requirement = minimum suitability
    if x >= fuel_q90:
        return 0.0

    # Linear inverse scaling between q10 and q90
    score = (
        (fuel_q90 - x)
        / (fuel_q90 - fuel_q10)
    )

    return np.clip(score, 0, 1)


# Apply fuel scoring
route_features_df["fuel_score"] = (
    route_features_df["fuel_l_proxy"]
    .apply(fuel_route_score)
)


# ------------------------------------------------------------
# Inspect results
# ------------------------------------------------------------

print("✅ Fuel suitability score calculated")

print("\nFuel score statistics:")
print(
    route_features_df["fuel_score"]
    .describe()
)

print("\nSample fuel scores:")

display(
    route_features_df[
        [
            "zone_id",
            "fuel_l_proxy",
            "fuel_score"
        ]
    ].head(15)
)

✅ Fuel suitability score calculated

Fuel score statistics:
count    2037.000000
mean        0.537399
std         0.355337
min         0.000000
25%         0.216356
50%         0.550809
75%         0.903812
max         1.000000
Name: fuel_score, dtype: float64

Sample fuel scores:

    zone_id  fuel_l_proxy  fuel_score
0   PFZ0001      8.888889    1.000000
1   PFZ0002      7.111111    1.000000
2   PFZ0003      3.555556    1.000000
3   PFZ0004     12.000000    1.000000
4   PFZ0005     14.666667    1.000000
5   PFZ0006     15.111111    0.997469
6   PFZ0007     12.888889    1.000000
7   PFZ0008     13.333333    1.000000
8   PFZ0009     12.000000    1.000000
9   PFZ0010     20.000000    0.969625
10  PFZ0011     14.666667    1.000000
11  PFZ0012      8.000000    1.000000
12  PFZ0013     12.000000    1.000000
13  PFZ0014      5.777778    1.000000
14  PFZ0015      7.555556    1.000000

In [ ]:
# ============================================================
# DIAGNOSTIC — CHECK RELATIONSHIP BETWEEN ROUTING VARIABLES
# ============================================================

check_cols = [
    "distance_km",
    "travel_time_hr",
    "fuel_l_proxy",
    "distance_score",
    "travel_time_score",
    "fuel_score"
]

print("CORRELATION MATRIX")
print("=" * 60)

display(
    route_features_df[check_cols]
    .corr(numeric_only=True)
)

print("\nSAMPLE VALUES")
print("=" * 60)

display(
    route_features_df[
        [
            "zone_id",
            "distance_km",
            "travel_time_hr",
            "fuel_l_proxy",
            "distance_score",
            "travel_time_score",
            "fuel_score"
        ]
    ].head(20)
)

CORRELATION MATRIX
============================================================

,distance_km,travel_time_hr,fuel_l_proxy,distance_score,travel_time_score,fuel_score
distance_km,1.000000,1.000000,1.000000,-0.997037,-0.997037,-0.997037
travel_time_hr,1.000000,1.000000,1.000000,-0.997037,-0.997037,-0.997037
fuel_l_proxy,1.000000,1.000000,1.000000,-0.997037,-0.997037,-0.997037
distance_score,-0.997037,-0.997037,-0.997037,1.000000,1.000000,1.000000
travel_time_score,-0.997037,-0.997037,-0.997037,1.000000,1.000000,1.000000
fuel_score,-0.997037,-0.997037,-0.997037,1.000000,1.000000,1.000000

SAMPLE VALUES
============================================================

,zone_id,distance_km,travel_time_hr,fuel_l_proxy,distance_score,travel_time_score,fuel_score
0,PFZ0001,20.0,1.111111,8.888889,1.000000,1.000000,1.000000
1,PFZ0002,16.0,0.888889,7.111111,1.000000,1.000000,1.000000
2,PFZ0003,8.0,0.444444,3.555556,1.000000,1.000000,1.000000
3,PFZ0004,27.0,1.500000,12.000000,1.000000,1.000000,1.000000
4,PFZ0005,33.0,1.833333,14.666667,1.000000,1.000000,1.000000
5,PFZ0006,34.0,1.888889,15.111111,0.997469,0.997469,0.997469
6,PFZ0007,29.0,1.611111,12.888889,1.000000,1.000000,1.000000
7,PFZ0008,30.0,1.666667,13.333333,1.000000,1.000000,1.000000
8,PFZ0009,27.0,1.500000,12.000000,1.000000,1.000000,1.000000
9,PFZ0010,45.0,2.500000,20.000000,0.969625,0.969625,0.969625
10,PFZ0011,33.0,1.833333,14.666667,1.000000,1.000000,1.000000
11,PFZ0012,18.0,1.000000,8.000000,1.000000,1.000000,1.000000
12,PFZ0013,27.0,1.500000,12.000000,1.000000,1.000000,1.000000
13,PFZ0014,13.0,0.722222,5.777778,1.000000,1.000000,1.000000
14,PFZ0015,17.0,0.944444,7.555556,1.000000,1.000000,1.000000
15,PFZ0016,20.0,1.111111,8.888889,1.000000,1.000000,1.000000
16,PFZ0017,17.0,0.944444,7.555556,1.000000,1.000000,1.000000
17,PFZ0018,20.0,1.111111,8.888889,1.000000,1.000000,1.000000
18,PFZ0019,22.0,1.222222,9.777778,1.000000,1.000000,1.000000
19,PFZ0020,26.0,1.444444,11.555556,1.000000,1.000000,1.000000

In [ ]:
# ============================================================
# DIAGNOSTIC — WHY ARE ROUTE COMPONENT SCORES SATURATING?
# ============================================================

for name, col in [
    ("Distance", "distance_km"),
    ("Travel Time", "travel_time_hr"),
    ("Fuel", "fuel_l_proxy")
]:
    print("\n" + "=" * 60)
    print(name)

    q10 = route_features_df[col].quantile(0.10)
    q50 = route_features_df[col].quantile(0.50)
    q90 = route_features_df[col].quantile(0.90)

    print(f"q10     : {q10:.6f}")
    print(f"median  : {q50:.6f}")
    print(f"q90     : {q90:.6f}")

    print(
        f"Values <= q10: "
        f"{(route_features_df[col] <= q10).sum()}"
    )

    print(
        f"Values >= q90: "
        f"{(route_features_df[col] >= q90).sum()}"
    )

print("\n\nSCORE DISTRIBUTIONS")
print("=" * 60)

for col in [
    "distance_score",
    "travel_time_score",
    "fuel_score"
]:
    print(
        f"\n{col}: "
        f"{route_features_df[col].nunique()} unique scores"
    )

    print(
        route_features_df[col]
        .value_counts()
        .head(10)
    )

============================================================
Distance
q10     : 33.000000
median  : 210.456495
q90     : 428.058288
Values <= q10: 208
Values >= q90: 204

============================================================
Travel Time
q10     : 1.833333
median  : 11.692028
q90     : 23.781016
Values <= q10: 208
Values >= q90: 204

============================================================
Fuel
q10     : 14.666667
median  : 93.536220
q90     : 190.248128
Values <= q10: 208
Values >= q90: 204


SCORE DISTRIBUTIONS
============================================================

distance_score: 1468 unique scores
distance_score
1.000000    208
0.000000    204
0.989875     11
0.979750     11
0.992406      9
0.997469      8
0.972156      8
0.982281      8
0.977219      8
0.994937      8
Name: count, dtype: int64

travel_time_score: 1468 unique scores
travel_time_score
1.000000    208
0.000000    204
0.989875     11
0.979750     11
0.992406      9
0.997469      8
0.972156      8
0.982281      8
0.977219      8
0.994937      8
Name: count, dtype: int64

fuel_score: 1468 unique scores
fuel_score
1.000000    208
0.000000    204
0.989875     11
0.979750     11
0.992406      9
0.997469      8
0.972156      8
0.982281      8
0.977219      8
0.994937      8
Name: count, dtype: int64

In [ ]:
# ============================================================
# STEP 5/6/7 DIAGNOSTIC — CHECK ROUTING VARIABLE RELATIONSHIPS
# ============================================================

raw_cols = [
    "distance_km",
    "travel_time_hr",
    "fuel_l_proxy"
]

print("RAW VARIABLE CORRELATION")
print("=" * 60)

display(
    route_features_df[raw_cols]
    .corr()
)

print("\nDERIVED RELATIONSHIPS")
print("=" * 60)

print(
    "Median travel time / distance:",
    (
        route_features_df["travel_time_hr"]
        / route_features_df["distance_km"]
    ).median()
)

print(
    "Median fuel / distance:",
    (
        route_features_df["fuel_l_proxy"]
        / route_features_df["distance_km"]
    ).median()
)

print("\nNUMBER OF UNIQUE VALUES")
print("=" * 60)

for col in raw_cols:
    print(
        f"{col}: "
        f"{route_features_df[col].nunique()} unique values"
    )

print("\nSCORE CORRELATION")
print("=" * 60)

score_cols = [
    "distance_score",
    "travel_time_score",
    "fuel_score"
]

display(
    route_features_df[score_cols]
    .corr()
)

RAW VARIABLE CORRELATION
============================================================

                distance_km  travel_time_hr  fuel_l_proxy
distance_km             1.0             1.0           1.0
travel_time_hr          1.0             1.0           1.0
fuel_l_proxy            1.0             1.0           1.0

DERIVED RELATIONSHIPS
============================================================
Median travel time / distance: 0.05555555555555555
Median fuel / distance: 0.4444444444444444

NUMBER OF UNIQUE VALUES
============================================================
distance_km: 1779 unique values
travel_time_hr: 1779 unique values
fuel_l_proxy: 1779 unique values

SCORE CORRELATION
============================================================

                   distance_score  travel_time_score  fuel_score
distance_score                1.0                1.0         1.0
travel_time_score             1.0                1.0         1.0
fuel_score                    1.0                1.0         1.0

In [ ]:
# ============================================================
# STEP 8: ROUTE EFFICIENCY SCORE
# ============================================================

# Because distance, travel time and fuel are perfectly correlated
# in this dataset, they are treated as one underlying
# route-efficiency dimension.

eff_q10 = route_features_df["distance_km"].quantile(0.10)
eff_q50 = route_features_df["distance_km"].quantile(0.50)
eff_q90 = route_features_df["distance_km"].quantile(0.90)


def route_efficiency_score(x):
    """
    Convert route distance into a normalized 0-1
    route-efficiency score.

    Lower route distance = higher efficiency.
    """

    if pd.isna(x):
        return np.nan

    if x <= eff_q10:
        return 1.0

    if x >= eff_q90:
        return 0.0

    score = (
        (eff_q90 - x)
        / (eff_q90 - eff_q10)
    )

    return np.clip(score, 0, 1)


route_features_df["efficiency_score"] = (
    route_features_df["distance_km"]
    .apply(route_efficiency_score)
)


print("✅ Route efficiency score calculated")

print("\nEfficiency reference values:")
print(f"Q10    : {eff_q10:.4f}")
print(f"Median : {eff_q50:.4f}")
print(f"Q90    : {eff_q90:.4f}")

print("\nEfficiency score statistics:")
display(
    route_features_df["efficiency_score"].describe()
)

print("\nSample:")
display(
    route_features_df[
        [
            "zone_id",
            "distance_km",
            "travel_time_hr",
            "fuel_l_proxy",
            "efficiency_score"
        ]
    ].head(15)
)

✅ Route efficiency score calculated

Efficiency reference values:
Q10    : 33.0000
Median : 210.4565
Q90    : 428.0583

Efficiency score statistics:

count    2037.000000
mean        0.537399
std         0.355337
min         0.000000
25%         0.216356
50%         0.550809
75%         0.903812
max         1.000000
Name: efficiency_score, dtype: float64

Sample:

    zone_id  distance_km  travel_time_hr  fuel_l_proxy  efficiency_score
0   PFZ0001         20.0        1.111111      8.888889          1.000000
1   PFZ0002         16.0        0.888889      7.111111          1.000000
2   PFZ0003          8.0        0.444444      3.555556          1.000000
3   PFZ0004         27.0        1.500000     12.000000          1.000000
4   PFZ0005         33.0        1.833333     14.666667          1.000000
5   PFZ0006         34.0        1.888889     15.111111          0.997469
6   PFZ0007         29.0        1.611111     12.888889          1.000000
7   PFZ0008         30.0        1.666667     13.333333          1.000000
8   PFZ0009         27.0        1.500000     12.000000          1.000000
9   PFZ0010         45.0        2.500000     20.000000          0.969625
10  PFZ0011         33.0        1.833333     14.666667          1.000000
11  PFZ0012         18.0        1.000000      8.000000          1.000000
12  PFZ0013         27.0        1.500000     12.000000          1.000000
13  PFZ0014         13.0        0.722222      5.777778          1.000000
14  PFZ0015         17.0        0.944444      7.555556          1.000000

In [ ]:
# STEP 8 — Build Route Score Training Dataset

# Features used by the Route Agent
route_input_features = [
    "distance_km",
    "travel_time_hr",
    "fuel_l_proxy",
    "water_depth_m",
    "geofence_caution",
    "inside_mpa",
    "mpa_distance_km",
    "mpa_caution",
    "eez_boundary_distance_km",
    "current_u_ms",
    "current_v_ms",
    "current_speed_ms"
]

# Keep only columns that actually exist
route_input_features = [
    col for col in route_input_features
    if col in route_df.columns
]

# Rows where the known route score is available
train_df = route_df[
    route_df["route_score"].notna()
].copy()

# Training inputs
X = train_df[route_input_features].copy()

# Target = route score
y = train_df["route_score"].copy()

# Convert all inputs to numeric
for col in X.columns:
    X[col] = pd.to_numeric(X[col], errors="coerce")

# Safety check
print("✅ Route training dataset created")

print("Training rows:", len(X))
print("Input features:", X.shape[1])

print("\nFeatures used:")
print(X.columns.tolist())

print("\nTarget:")
print("route_score")

print("\nMissing values in training inputs:")
print(X.isnull().sum())

print("\nTarget range:")
print("Min:", y.min())
print("Max:", y.max())

✅ Route training dataset created
Training rows: 1542
Input features: 12

Features used:
['distance_km', 'travel_time_hr', 'fuel_l_proxy', 'water_depth_m', 'geofence_caution', 'inside_mpa', 'mpa_distance_km', 'mpa_caution', 'eez_boundary_distance_km', 'current_u_ms', 'current_v_ms', 'current_speed_ms']

Target:
route_score

Missing values in training inputs:
distance_km                 0
travel_time_hr              0
fuel_l_proxy                0
water_depth_m               0
geofence_caution            0
inside_mpa                  0
mpa_distance_km             0
mpa_caution                 0
eez_boundary_distance_km    0
current_u_ms                0
current_v_ms                0
current_speed_ms            0
dtype: int64

Target range:
Min: 0.5089100333333334
Max: 0.99911611655

In [ ]:
# ============================================================
# STEP 9: DATA-DRIVEN ROUTE SAFETY REFERENCE PARAMETERS
# ============================================================

print("ROUTE SAFETY REFERENCE PARAMETERS")
print("=" * 60)

# ------------------------------------------------------------
# 1. Water depth
# ------------------------------------------------------------

depth_q10 = route_features_df["water_depth_m"].quantile(0.10)
depth_q50 = route_features_df["water_depth_m"].quantile(0.50)
depth_q90 = route_features_df["water_depth_m"].quantile(0.90)


# ------------------------------------------------------------
# 2. Distance from MPA
# ------------------------------------------------------------

mpa_q10 = route_features_df["mpa_distance_km"].quantile(0.10)
mpa_q50 = route_features_df["mpa_distance_km"].quantile(0.50)
mpa_q90 = route_features_df["mpa_distance_km"].quantile(0.90)


# ------------------------------------------------------------
# 3. Distance from EEZ boundary
# ------------------------------------------------------------

eez_q10 = route_features_df[
    "eez_boundary_distance_km"
].quantile(0.10)

eez_q50 = route_features_df[
    "eez_boundary_distance_km"
].quantile(0.50)

eez_q90 = route_features_df[
    "eez_boundary_distance_km"
].quantile(0.90)


# ------------------------------------------------------------
# 4. Current speed
# ------------------------------------------------------------

current_q10 = route_features_df[
    "current_speed_ms"
].quantile(0.10)

current_q50 = route_features_df[
    "current_speed_ms"
].quantile(0.50)

current_q90 = route_features_df[
    "current_speed_ms"
].quantile(0.90)


# ------------------------------------------------------------
# 5. Display reference values
# ------------------------------------------------------------

print("\nWater Depth:")
print(f"10th percentile : {depth_q10:.4f}")
print(f"Median          : {depth_q50:.4f}")
print(f"90th percentile : {depth_q90:.4f}")

print("\nMPA Distance:")
print(f"10th percentile : {mpa_q10:.4f}")
print(f"Median          : {mpa_q50:.4f}")
print(f"90th percentile : {mpa_q90:.4f}")

print("\nEEZ Boundary Distance:")
print(f"10th percentile : {eez_q10:.4f}")
print(f"Median          : {eez_q50:.4f}")
print(f"90th percentile : {eez_q90:.4f}")

print("\nCurrent Speed:")
print(f"10th percentile : {current_q10:.4f}")
print(f"Median          : {current_q50:.4f}")
print(f"90th percentile : {current_q90:.4f}")


# ------------------------------------------------------------
# 6. Constraint availability
# ------------------------------------------------------------

print("\nConstraint availability:")
print("=" * 60)

for col in [
    "geofence_caution",
    "inside_mpa",
    "mpa_caution"
]:
    available = route_features_df[col].notna().sum()
    total = len(route_features_df)

    print(
        f"{col}: "
        f"{available}/{total} available "
        f"({available / total * 100:.2f}%)"
    )

ROUTE SAFETY REFERENCE PARAMETERS
============================================================

Water Depth:
10th percentile : 0.0000
Median          : 1267.0000
90th percentile : 3580.0000

MPA Distance:
10th percentile : 70.1678
Median          : 327.9522
90th percentile : 1186.9220

EEZ Boundary Distance:
10th percentile : 17.0723
Median          : 74.3141
90th percentile : 217.5632

Current Speed:
10th percentile : 0.0424
Median          : 0.1226
90th percentile : 0.2711

Constraint availability:
============================================================
geofence_caution: 2037/2037 available (100.00%)
inside_mpa: 2037/2037 available (100.00%)
mpa_caution: 2037/2037 available (100.00%)

In [ ]:
# ============================================================
# STEP 10: WATER-DEPTH ROUTE SAFETY SCORE
# ============================================================

def depth_safety_score(x):
    """
    Convert water depth into a 0-1 route-safety score.

    Very shallow water = lower safety.
    Adequate water depth = higher safety.

    Dataset-derived references:
    q10  -> lower-depth reference
    q50  -> adequate-depth benchmark
    """

    if pd.isna(x):
        return np.nan

    # At or below the lower reference:
    # treat as lowest depth suitability
    if x <= depth_q10:
        return 0.0

    # At or above the median:
    # treat as adequate depth for this dataset
    if x >= depth_q50:
        return 1.0

    # Linear increase between q10 and median
    score = (
        (x - depth_q10)
        / (depth_q50 - depth_q10)
    )

    return np.clip(score, 0, 1)


# Apply depth safety scoring
route_features_df["depth_safety_score"] = (
    route_features_df["water_depth_m"]
    .apply(depth_safety_score)
)


# ------------------------------------------------------------
# Inspect results
# ------------------------------------------------------------

print("✅ Water-depth safety score calculated")

print("\nDepth reference values:")
print(f"Q10    : {depth_q10:.4f}")
print(f"Median : {depth_q50:.4f}")
print(f"Q90    : {depth_q90:.4f}")

print("\nDepth safety-score statistics:")
display(
    route_features_df["depth_safety_score"].describe()
)

print("\nSample:")
display(
    route_features_df[
        [
            "zone_id",
            "water_depth_m",
            "depth_safety_score"
        ]
    ].head(20)
)

✅ Water-depth safety score calculated

Depth reference values:
Q10    : 0.0000
Median : 1267.0000
Q90    : 3580.0000

Depth safety-score statistics:

count    2037.000000
mean        0.559991
std         0.470525
min         0.000000
25%         0.022889
50%         1.000000
75%         1.000000
max         1.000000
Name: depth_safety_score, dtype: float64

Sample:

    zone_id  water_depth_m  depth_safety_score
0   PFZ0001           20.0            0.015785
1   PFZ0002          102.0            0.080505
2   PFZ0003           75.0            0.059195
3   PFZ0004          249.0            0.196527
4   PFZ0005          230.0            0.181531
5   PFZ0006          453.0            0.357537
6   PFZ0007          499.0            0.393844
7   PFZ0008          468.0            0.369376
8   PFZ0009          601.0            0.474349
9   PFZ0010         1149.0            0.906867
10  PFZ0011         1066.0            0.841358
11  PFZ0012          933.0            0.736385
12  PFZ0013         1101.0            0.868982
13  PFZ0014           38.0            0.029992
14  PFZ0015          189.0            0.149171
15  PFZ0016          254.0            0.200474
16  PFZ0017          372.0            0.293607
17  PFZ0018           64.0            0.050513
18  PFZ0019          655.0            0.516969
19  PFZ0020         1237.0            0.976322

In [ ]:
# ============================================================
# STEP 11: MPA / GEOFENCE CONSTRAINT INSPECTION
# ============================================================

constraint_cols = [
    "inside_mpa",
    "mpa_caution",
    "geofence_caution"
]

print("ROUTE CONSTRAINT INSPECTION")
print("=" * 60)

# ------------------------------------------------------------
# 1. Unique values and counts
# ------------------------------------------------------------

for col in constraint_cols:
    print(f"\n--- {col} ---")

    print("Unique values:")
    print(route_features_df[col].dropna().unique())

    print("\nValue counts:")
    print(
        route_features_df[col]
        .value_counts(dropna=False)
    )


# ------------------------------------------------------------
# 2. MPA status vs MPA caution
# ------------------------------------------------------------

print("\n\nMPA STATUS × MPA CAUTION")
print("=" * 60)

display(
    pd.crosstab(
        route_features_df["inside_mpa"],
        route_features_df["mpa_caution"],
        dropna=False
    )
)


# ------------------------------------------------------------
# 3. Geofence caution by value
# ------------------------------------------------------------

print("\nGEOFENCE CAUTION")
print("=" * 60)

display(
    route_features_df[
        [
            "zone_id",
            "geofence_caution",
            "inside_mpa",
            "mpa_caution"
        ]
    ].head(20)
)

ROUTE CONSTRAINT INSPECTION
============================================================

--- inside_mpa ---
Unique values:
[0 1]

Value counts:
inside_mpa
0    2032
1       5
Name: count, dtype: int64

--- mpa_caution ---
Unique values:
[0 1]

Value counts:
mpa_caution
0    2026
1      11
Name: count, dtype: int64

--- geofence_caution ---
Unique values:
[0 1]

Value counts:
geofence_caution
0    1987
1      50
Name: count, dtype: int64


MPA STATUS × MPA CAUTION
============================================================

mpa_caution     0  1
inside_mpa
0            2026  6
1               0  5

GEOFENCE CAUTION
============================================================

    zone_id  geofence_caution  inside_mpa  mpa_caution
0   PFZ0001                 0           0            0
1   PFZ0002                 0           0            0
2   PFZ0003                 0           0            0
3   PFZ0004                 0           0            0
4   PFZ0005                 0           0            0
5   PFZ0006                 0           0            0
6   PFZ0007                 0           0            0
7   PFZ0008                 0           0            0
8   PFZ0009                 0           0            0
9   PFZ0010                 0           0            0
10  PFZ0011                 0           0            0
11  PFZ0012                 0           0            0
12  PFZ0013                 0           0            0
13  PFZ0014                 0           0            0
14  PFZ0015                 0           0            0
15  PFZ0016                 0           0            0
16  PFZ0017                 0           0            0
17  PFZ0018                 1           0            0
18  PFZ0019                 0           0            0
19  PFZ0020                 0           0            0

In [ ]:
# ============================================================
# STEP 12: ROUTE CONSTRAINT SAFETY SCORE
# ============================================================

def constraint_safety_score(row):
    """
    Calculate a 0-1 route constraint safety score.

    Each available constraint check contributes equally.

    1 = no constraint warning
    0 = constraint warning / restricted condition
    """

    checks = []

    # --------------------------------------------------------
    # MPA occupancy
    # --------------------------------------------------------
    if pd.notna(row["inside_mpa"]):
        checks.append(
            0.0 if int(row["inside_mpa"]) == 1 else 1.0
        )

    # --------------------------------------------------------
    # MPA caution
    # --------------------------------------------------------
    if pd.notna(row["mpa_caution"]):
        checks.append(
            0.0 if int(row["mpa_caution"]) == 1 else 1.0
        )

    # --------------------------------------------------------
    # Geofence caution
    # --------------------------------------------------------
    if pd.notna(row["geofence_caution"]):
        checks.append(
            0.0 if int(row["geofence_caution"]) == 1 else 1.0
        )

    # No constraint information available
    if len(checks) == 0:
        return np.nan

    return np.clip(
        sum(checks) / len(checks),
        0,
        1
    )


# Apply constraint scoring
route_features_df["constraint_safety_score"] = (
    route_features_df.apply(
        constraint_safety_score,
        axis=1
    )
)


# ------------------------------------------------------------
# Inspect results
# ------------------------------------------------------------

print("✅ Constraint safety score calculated")

print("\nConstraint safety-score distribution:")
print(
    route_features_df[
        "constraint_safety_score"
    ].value_counts(dropna=False)
)

print("\nSample:")
display(
    route_features_df[
        [
            "zone_id",
            "inside_mpa",
            "mpa_caution",
            "geofence_caution",
            "constraint_safety_score"
        ]
    ].head(20)
)

✅ Constraint safety score calculated

Constraint safety-score distribution:
constraint_safety_score
1.000000    1976
0.666667      56
0.333333       5
Name: count, dtype: int64

Sample:

,zone_id,inside_mpa,mpa_caution,geofence_caution,constraint_safety_score
0,PFZ0001,0,0,0,1.000000
1,PFZ0002,0,0,0,1.000000
2,PFZ0003,0,0,0,1.000000
3,PFZ0004,0,0,0,1.000000
4,PFZ0005,0,0,0,1.000000
5,PFZ0006,0,0,0,1.000000
6,PFZ0007,0,0,0,1.000000
7,PFZ0008,0,0,0,1.000000
8,PFZ0009,0,0,0,1.000000
9,PFZ0010,0,0,0,1.000000
10,PFZ0011,0,0,0,1.000000
11,PFZ0012,0,0,0,1.000000
12,PFZ0013,0,0,0,1.000000
13,PFZ0014,0,0,0,1.000000
14,PFZ0015,0,0,0,1.000000
15,PFZ0016,0,0,0,1.000000
16,PFZ0017,0,0,0,1.000000
17,PFZ0018,0,0,1,0.666667
18,PFZ0019,0,0,0,1.000000
19,PFZ0020,0,0,0,1.000000

In [ ]:
# ============================================================
# STEP 13: CURRENT-BASED ROUTE SAFETY SCORE
# ============================================================

# Dataset-derived current references
current_safety_q10 = route_features_df[
    "current_speed_ms"
].quantile(0.10)

current_safety_q50 = route_features_df[
    "current_speed_ms"
].quantile(0.50)

current_safety_q90 = route_features_df[
    "current_speed_ms"
].quantile(0.90)


def current_safety_score(x):
    """
    Convert current speed into a 0-1 route-safety score.

    Lower current magnitude = higher route-safety score.

    Missing current data remains missing.
    """

    if pd.isna(x):
        return np.nan

    # Low current magnitude
    if x <= current_safety_q10:
        return 1.0

    # High current magnitude
    if x >= current_safety_q90:
        return 0.0

    # Inverse linear scaling
    score = (
        (current_safety_q90 - x)
        / (
            current_safety_q90
            - current_safety_q10
        )
    )

    return np.clip(score, 0, 1)


# Apply current safety scoring
route_features_df["current_safety_score"] = (
    route_features_df["current_speed_ms"]
    .apply(current_safety_score)
)


# ------------------------------------------------------------
# Inspect results
# ------------------------------------------------------------

print("✅ Current-based route safety score calculated")

print("\nCurrent references:")
print(
    f"Q10    : {current_safety_q10:.6f}"
)
print(
    f"Median : {current_safety_q50:.6f}"
)
print(
    f"Q90    : {current_safety_q90:.6f}"
)

print("\nCurrent safety score statistics:")
display(
    route_features_df[
        "current_safety_score"
    ].describe()
)

print("\nSample:")
display(
    route_features_df[
        [
            "zone_id",
            "current_speed_ms",
            "current_safety_score"
        ]
    ].head(20)
)

✅ Current-based route safety score calculated

Current references:
Q10    : 0.042440
Median : 0.122623
Q90    : 0.271145

Current safety score statistics:

count    1542.000000
mean        0.582953
std         0.332523
min         0.000000
25%         0.323686
50%         0.649402
75%         0.875709
max         1.000000
Name: current_safety_score, dtype: float64

Sample:

    zone_id  current_speed_ms  current_safety_score
0   PFZ0001               NaN                   NaN
1   PFZ0002               NaN                   NaN
2   PFZ0003               NaN                   NaN
3   PFZ0004               NaN                   NaN
4   PFZ0005               NaN                   NaN
5   PFZ0006          0.058917              0.927953
6   PFZ0007          0.058917              0.927953
7   PFZ0008          0.058917              0.927953
8   PFZ0009          0.058917              0.927953
9   PFZ0010          0.070516              0.877238
10  PFZ0011          0.070516              0.877238
11  PFZ0012          0.070516              0.877238
12  PFZ0013          0.031906              1.000000
13  PFZ0014          0.051159              0.961875
14  PFZ0015          0.041773              1.000000
15  PFZ0016          0.051159              0.961875
16  PFZ0017          0.040265              1.000000
17  PFZ0018          0.009124              1.000000
18  PFZ0019          0.040265              1.000000
19  PFZ0020          0.040265              1.000000

In [ ]:
# ============================================================
# STEP 14: COMBINED ROUTE SAFETY SCORE
# ============================================================

safety_weights = {
    "depth_safety_score": 1 / 3,
    "constraint_safety_score": 1 / 3,
    "current_safety_score": 1 / 3
}


def calculate_route_safety_score(row):
    """
    Combine independent route-safety components.

    Missing components are excluded and the remaining
    weights are re-normalized.
    """

    available = []

    for feature, weight in safety_weights.items():

        if pd.notna(row[feature]):
            available.append(
                (row[feature], weight)
            )

    # No safety information available
    if len(available) == 0:
        return np.nan

    total_weight = sum(
        weight for score, weight in available
    )

    score = sum(
        score * weight
        for score, weight in available
    ) / total_weight

    return np.clip(score, 0, 1)


# ------------------------------------------------------------
# Apply combined safety score
# ------------------------------------------------------------

route_features_df["route_safety_score"] = (
    route_features_df.apply(
        calculate_route_safety_score,
        axis=1
    )
)


# ------------------------------------------------------------
# Safety confidence
# ------------------------------------------------------------

route_features_df["route_safety_confidence"] = (
    route_features_df[
        [
            "depth_safety_score",
            "constraint_safety_score",
            "current_safety_score"
        ]
    ]
    .notna()
    .sum(axis=1)
    / 3
)


# ------------------------------------------------------------
# Inspect results
# ------------------------------------------------------------

print("✅ Combined route safety score calculated")

print("\nRoute safety score statistics:")
display(
    route_features_df[
        "route_safety_score"
    ].describe()
)

print("\nRoute safety confidence statistics:")
display(
    route_features_df[
        "route_safety_confidence"
    ].describe()
)

print("\nSample:")
display(
    route_features_df[
        [
            "zone_id",
            "depth_safety_score",
            "constraint_safety_score",
            "current_safety_score",
            "route_safety_score",
            "route_safety_confidence"
        ]
    ].head(20)
)

✅ Combined route safety score calculated

Route safety score statistics:

count    2037.000000
mean        0.704647
std         0.180928
min         0.166667
25%         0.500000
50%         0.682148
75%         0.869400
max         1.000000
Name: route_safety_score, dtype: float64

Route safety confidence statistics:

count    2037.000000
mean        0.918999
std         0.143001
min         0.666667
25%         1.000000
50%         1.000000
75%         1.000000
max         1.000000
Name: route_safety_confidence, dtype: float64

Sample:

,zone_id,depth_safety_score,constraint_safety_score,current_safety_score,route_safety_score,route_safety_confidence
0,PFZ0001,0.015785,1.000000,NaN,0.507893,0.666667
1,PFZ0002,0.080505,1.000000,NaN,0.540253,0.666667
2,PFZ0003,0.059195,1.000000,NaN,0.529597,0.666667
3,PFZ0004,0.196527,1.000000,NaN,0.598264,0.666667
4,PFZ0005,0.181531,1.000000,NaN,0.590766,0.666667
5,PFZ0006,0.357537,1.000000,0.927953,0.761830,1.000000
6,PFZ0007,0.393844,1.000000,0.927953,0.773932,1.000000
7,PFZ0008,0.369376,1.000000,0.927953,0.765776,1.000000
8,PFZ0009,0.474349,1.000000,0.927953,0.800767,1.000000
9,PFZ0010,0.906867,1.000000,0.877238,0.928035,1.000000
10,PFZ0011,0.841358,1.000000,0.877238,0.906199,1.000000
11,PFZ0012,0.736385,1.000000,0.877238,0.871208,1.000000
12,PFZ0013,0.868982,1.000000,1.000000,0.956327,1.000000
13,PFZ0014,0.029992,1.000000,0.961875,0.663956,1.000000
14,PFZ0015,0.149171,1.000000,1.000000,0.716390,1.000000
15,PFZ0016,0.200474,1.000000,0.961875,0.720783,1.000000
16,PFZ0017,0.293607,1.000000,1.000000,0.764536,1.000000
17,PFZ0018,0.050513,0.666667,1.000000,0.572393,1.000000
18,PFZ0019,0.516969,1.000000,1.000000,0.838990,1.000000
19,PFZ0020,0.976322,1.000000,1.000000,0.992107,1.000000

In [ ]:
# ============================================================
# STEP 15: FINAL ROUTE SCORE
# ============================================================

# ------------------------------------------------------------
# Route-score weights
# Screenshot specifies:
# Distance + Time + Fuel + Route Safety
#
# Distance/Time/Fuel are perfectly correlated in this dataset,
# so they are represented by ONE efficiency component.
#
# No numerical weights were specified in the workflow,
# therefore use neutral equal weighting:
#   Efficiency = 50%
#   Safety     = 50%
# ------------------------------------------------------------

route_score_weights = {
    "efficiency_score": 0.50,
    "route_safety_score": 0.50
}


def calculate_route_score(row):
    """
    Calculate final 0-1 Route Score.

    Missing components are excluded and the remaining
    weights are re-normalized.
    """

    available = []

    for feature, weight in route_score_weights.items():

        if pd.notna(row[feature]):
            available.append(
                (row[feature], weight)
            )

    # No usable routing information
    if len(available) == 0:
        return np.nan

    total_weight = sum(
        weight for score, weight in available
    )

    score = sum(
        score * weight
        for score, weight in available
    ) / total_weight

    return np.clip(score, 0, 1)


# ------------------------------------------------------------
# Calculate final Route Score
# ------------------------------------------------------------

route_features_df["route_score_calculated"] = (
    route_features_df.apply(
        calculate_route_score,
        axis=1
    )
)


# ------------------------------------------------------------
# Overall route confidence
# ------------------------------------------------------------

route_features_df["route_confidence"] = (
    route_features_df[
        [
            "efficiency_score",
            "route_safety_score"
        ]
    ]
    .notna()
    .sum(axis=1)
    / 2
)


# ------------------------------------------------------------
# Confidence-adjusted Route Score
# ------------------------------------------------------------

route_features_df["adjusted_route_score"] = (
    route_features_df["route_score_calculated"]
    * route_features_df["route_confidence"]
)


# ------------------------------------------------------------
# Inspect result
# ------------------------------------------------------------

print("✅ Final Route Score calculated")

print("\nRoute Score statistics:")
display(
    route_features_df[
        "route_score_calculated"
    ].describe()
)

print("\nRoute Confidence:")
display(
    route_features_df[
        "route_confidence"
    ].value_counts(dropna=False)
)

print("\nSample Route Scores:")

display(
    route_features_df[
        [
            "zone_id",
            "distance_km",
            "travel_time_hr",
            "fuel_l_proxy",
            "efficiency_score",
            "route_safety_score",
            "route_score_calculated",
            "route_confidence",
            "adjusted_route_score"
        ]
    ].head(20)
)

✅ Final Route Score calculated

Route Score statistics:

count    2037.000000
mean        0.621023
std         0.188941
min         0.168640
25%         0.472497
50%         0.632112
75%         0.778320
max         1.000000
Name: route_score_calculated, dtype: float64

Route Confidence:

route_confidence
1.0    2037
Name: count, dtype: int64

Sample Route Scores:

,zone_id,distance_km,travel_time_hr,fuel_l_proxy,efficiency_score,route_safety_score,route_score_calculated,route_confidence,adjusted_route_score
0,PFZ0001,20.0,1.111111,8.888889,1.000000,0.507893,0.753946,1.0,0.753946
1,PFZ0002,16.0,0.888889,7.111111,1.000000,0.540253,0.770126,1.0,0.770126
2,PFZ0003,8.0,0.444444,3.555556,1.000000,0.529597,0.764799,1.0,0.764799
3,PFZ0004,27.0,1.500000,12.000000,1.000000,0.598264,0.799132,1.0,0.799132
4,PFZ0005,33.0,1.833333,14.666667,1.000000,0.590766,0.795383,1.0,0.795383
5,PFZ0006,34.0,1.888889,15.111111,0.997469,0.761830,0.879649,1.0,0.879649
6,PFZ0007,29.0,1.611111,12.888889,1.000000,0.773932,0.886966,1.0,0.886966
7,PFZ0008,30.0,1.666667,13.333333,1.000000,0.765776,0.882888,1.0,0.882888
8,PFZ0009,27.0,1.500000,12.000000,1.000000,0.800767,0.900384,1.0,0.900384
9,PFZ0010,45.0,2.500000,20.000000,0.969625,0.928035,0.948830,1.0,0.948830
10,PFZ0011,33.0,1.833333,14.666667,1.000000,0.906199,0.953099,1.0,0.953099
11,PFZ0012,18.0,1.000000,8.000000,1.000000,0.871208,0.935604,1.0,0.935604
12,PFZ0013,27.0,1.500000,12.000000,1.000000,0.956327,0.978164,1.0,0.978164
13,PFZ0014,13.0,0.722222,5.777778,1.000000,0.663956,0.831978,1.0,0.831978
14,PFZ0015,17.0,0.944444,7.555556,1.000000,0.716390,0.858195,1.0,0.858195
15,PFZ0016,20.0,1.111111,8.888889,1.000000,0.720783,0.860391,1.0,0.860391
16,PFZ0017,17.0,0.944444,7.555556,1.000000,0.764536,0.882268,1.0,0.882268
17,PFZ0018,20.0,1.111111,8.888889,1.000000,0.572393,0.786197,1.0,0.786197
18,PFZ0019,22.0,1.222222,9.777778,1.000000,0.838990,0.919495,1.0,0.919495
19,PFZ0020,26.0,1.444444,11.555556,1.000000,0.992107,0.996054,1.0,0.996054

In [ ]:
# ============================================================
# STEP 16: ROUTE DATA COMPLETENESS / CONFIDENCE
# ============================================================

# Core routing information
core_route_features = [
    "distance_km",
    "travel_time_hr",
    "fuel_l_proxy",
    "water_depth_m",
    "current_speed_ms"
]

print("ROUTE DATA COMPLETENESS")
print("=" * 60)

# Number of available core routing features
route_features_df["route_core_features_available"] = (
    route_features_df[core_route_features]
    .notna()
    .sum(axis=1)
)

# Completeness = available / total
route_features_df["route_data_completeness"] = (
    route_features_df["route_core_features_available"]
    / len(core_route_features)
)

# Confidence follows completeness
route_features_df["route_confidence"] = (
    route_features_df["route_data_completeness"]
)


# ------------------------------------------------------------
# Inspect confidence
# ------------------------------------------------------------

print("\nConfidence distribution:")
print(
    route_features_df[
        "route_confidence"
    ].value_counts(dropna=False)
)

print("\nConfidence statistics:")
display(
    route_features_df[
        "route_confidence"
    ].describe()
)

print("\nSample:")
display(
    route_features_df[
        [
            "zone_id",
            "distance_km",
            "travel_time_hr",
            "fuel_l_proxy",
            "water_depth_m",
            "current_speed_ms",
            "route_core_features_available",
            "route_data_completeness",
            "route_confidence"
        ]
    ].head(20)
)

ROUTE DATA COMPLETENESS
============================================================

Confidence distribution:
route_confidence
1.0    1542
0.8     495
Name: count, dtype: int64

Confidence statistics:

count    2037.000000
mean        0.951399
std         0.085801
min         0.800000
25%         1.000000
50%         1.000000
75%         1.000000
max         1.000000
Name: route_confidence, dtype: float64

Sample:

,zone_id,distance_km,travel_time_hr,fuel_l_proxy,water_depth_m,current_speed_ms,route_core_features_available,route_data_completeness,route_confidence
0,PFZ0001,20.0,1.111111,8.888889,20.0,NaN,4,0.8,0.8
1,PFZ0002,16.0,0.888889,7.111111,102.0,NaN,4,0.8,0.8
2,PFZ0003,8.0,0.444444,3.555556,75.0,NaN,4,0.8,0.8
3,PFZ0004,27.0,1.500000,12.000000,249.0,NaN,4,0.8,0.8
4,PFZ0005,33.0,1.833333,14.666667,230.0,NaN,4,0.8,0.8
5,PFZ0006,34.0,1.888889,15.111111,453.0,0.058917,5,1.0,1.0
6,PFZ0007,29.0,1.611111,12.888889,499.0,0.058917,5,1.0,1.0
7,PFZ0008,30.0,1.666667,13.333333,468.0,0.058917,5,1.0,1.0
8,PFZ0009,27.0,1.500000,12.000000,601.0,0.058917,5,1.0,1.0
9,PFZ0010,45.0,2.500000,20.000000,1149.0,0.070516,5,1.0,1.0
10,PFZ0011,33.0,1.833333,14.666667,1066.0,0.070516,5,1.0,1.0
11,PFZ0012,18.0,1.000000,8.000000,933.0,0.070516,5,1.0,1.0
12,PFZ0013,27.0,1.500000,12.000000,1101.0,0.031906,5,1.0,1.0
13,PFZ0014,13.0,0.722222,5.777778,38.0,0.051159,5,1.0,1.0
14,PFZ0015,17.0,0.944444,7.555556,189.0,0.041773,5,1.0,1.0
15,PFZ0016,20.0,1.111111,8.888889,254.0,0.051159,5,1.0,1.0
16,PFZ0017,17.0,0.944444,7.555556,372.0,0.040265,5,1.0,1.0
17,PFZ0018,20.0,1.111111,8.888889,64.0,0.009124,5,1.0,1.0
18,PFZ0019,22.0,1.222222,9.777778,655.0,0.040265,5,1.0,1.0
19,PFZ0020,26.0,1.444444,11.555556,1237.0,0.040265,5,1.0,1.0

In [ ]:
# ============================================================
# STEP 17: ROUTE SCORE VALIDATION
# ============================================================

print("===== ROUTE SCORE VALIDATION =====")

# ------------------------------------------------------------
# 1. Calculated score range
# ------------------------------------------------------------

print("\nCalculated Route Score range:")
print(
    "Minimum:",
    route_features_df["route_score_calculated"].min()
)
print(
    "Maximum:",
    route_features_df["route_score_calculated"].max()
)


# ------------------------------------------------------------
# 2. Missing calculated scores
# ------------------------------------------------------------

print("\nMissing calculated Route Scores:")
print(
    route_features_df["route_score_calculated"]
    .isna()
    .sum()
)


# ------------------------------------------------------------
# 3. Calculated score distribution
# ------------------------------------------------------------

print("\nCalculated Route Score distribution:")
print(
    route_features_df[
        "route_score_calculated"
    ].describe()
)


# ------------------------------------------------------------
# 4. Compare with original dataset score
#    VALIDATION ONLY
# ------------------------------------------------------------

comparison_df = route_features_df[
    [
        "zone_id",
        "route_score_calculated",
        "route_score"
    ]
].dropna(
    subset=[
        "route_score_calculated",
        "route_score"
    ]
).copy()

print("\nValidation rows with original route_score:")
print(len(comparison_df))


# ------------------------------------------------------------
# 5. Validation error
# ------------------------------------------------------------

comparison_df["absolute_error"] = (
    comparison_df["route_score_calculated"]
    - comparison_df["route_score"]
).abs()

print("\nValidation error:")
print(
    comparison_df["absolute_error"].describe()
)


# ------------------------------------------------------------
# 6. Correlation
# ------------------------------------------------------------

print("\nCorrelation with supplied route_score:")
print(
    comparison_df[
        [
            "route_score_calculated",
            "route_score"
        ]
    ].corr().iloc[0, 1]
)


# ------------------------------------------------------------
# 7. Lowest calculated scores
# ------------------------------------------------------------

print("\nBottom 10 calculated routes:")

display(
    route_features_df[
        [
            "zone_id",
            "region",
            "route_score_calculated",
            "route_confidence",
            "adjusted_route_score"
        ]
    ]
    .dropna(subset=["route_score_calculated"])
    .sort_values(
        "route_score_calculated",
        ascending=True
    )
    .head(10)
)


# ------------------------------------------------------------
# 8. Highest calculated scores
# ------------------------------------------------------------

print("\nTop 10 calculated routes:")

display(
    route_features_df[
        [
            "zone_id",
            "region",
            "route_score_calculated",
            "route_confidence",
            "adjusted_route_score"
        ]
    ]
    .dropna(subset=["route_score_calculated"])
    .sort_values(
        "route_score_calculated",
        ascending=False
    )
    .head(10)
)

===== ROUTE SCORE VALIDATION =====

Calculated Route Score range:
Minimum: 0.16863983162325702
Maximum: 1.0

Missing calculated Route Scores:
0

Calculated Route Score distribution:
count    2037.000000
mean        0.621023
std         0.188941
min         0.168640
25%         0.472497
50%         0.632112
75%         0.778320
max         1.000000
Name: route_score_calculated, dtype: float64

Validation rows with original route_score:
1542

Validation error:
count    1542.000000
mean        0.290536
std         0.173820
min         0.000291
25%         0.150319
50%         0.257678
75%         0.436338
max         0.728585
Name: absolute_error, dtype: float64

Correlation with supplied route_score:
0.15687112289417562

Bottom 10 calculated routes:

,zone_id,region,route_score_calculated,route_confidence,adjusted_route_score
772,GRID_0436,INDIAN_MARINE,0.168640,1.0,0.168640
707,GRID_0371,INDIAN_MARINE,0.173770,1.0,0.173770
765,GRID_0429,INDIAN_MARINE,0.184577,0.8,0.184577
1136,GRID_0800,INDIAN_MARINE,0.191397,1.0,0.191397
1373,GRID_1037,INDIAN_MARINE,0.195212,0.8,0.195212
1143,GRID_0807,INDIAN_MARINE,0.232044,1.0,0.232044
871,GRID_0535,INDIAN_MARINE,0.232702,1.0,0.232702
592,GRID_0256,INDIAN_MARINE,0.239405,1.0,0.239405
767,GRID_0431,INDIAN_MARINE,0.244056,1.0,0.244056
1137,GRID_0801,INDIAN_MARINE,0.249063,1.0,0.249063

Top 10 calculated routes:

,zone_id,region,route_score_calculated,route_confidence,adjusted_route_score
168,PFZ0169,LAKSHADWEEP,1.000000,1.0,1.000000
1226,GRID_0890,INDIAN_MARINE,1.000000,1.0,1.000000
170,PFZ0171,LAKSHADWEEP,1.000000,1.0,1.000000
1828,GRID_1492,INDIAN_MARINE,1.000000,0.8,1.000000
811,GRID_0475,INDIAN_MARINE,1.000000,1.0,1.000000
1822,GRID_1486,INDIAN_MARINE,0.998172,1.0,0.998172
19,PFZ0020,ANDAMAN,0.996054,1.0,0.996054
327,PFZ0328,SOUTH ANDHRAPRADESH,0.993672,0.8,0.993672
985,GRID_0649,INDIAN_MARINE,0.992625,1.0,0.992625
544,GRID_0208,INDIAN_MARINE,0.991184,1.0,0.991184

In [ ]:
# ============================================================
# STEP 18: ROUTE SCORE DIAGNOSTIC
# ============================================================

diagnostic_cols = [
    "route_score",
    "distance_km",
    "travel_time_hr",
    "fuel_l_proxy",
    "water_depth_m",
    "current_speed_ms",
    "mpa_distance_km",
    "eez_boundary_distance_km",
    "inside_mpa",
    "mpa_caution",
    "geofence_caution",
    "route_score_calculated",
    "route_safety_score",
    "efficiency_score"
]

diagnostic_df = route_features_df[
    diagnostic_cols
].copy()

print("CORRELATION WITH SUPPLIED ROUTE SCORE")
print("=" * 60)

display(
    diagnostic_df.corr(numeric_only=True)["route_score"]
    .sort_values(ascending=False)
)

print("\n\nROUTE SCORE BY CONSTRAINT")
print("=" * 60)

print("\nInside MPA:")
display(
    diagnostic_df.groupby("inside_mpa")["route_score"]
    .agg(["count", "mean", "min", "max"])
)

print("\nMPA caution:")
display(
    diagnostic_df.groupby("mpa_caution")["route_score"]
    .agg(["count", "mean", "min", "max"])
)

print("\nGeofence caution:")
display(
    diagnostic_df.groupby("geofence_caution")["route_score"]
    .agg(["count", "mean", "min", "max"])
)

print("\n\nROUTE SCORE SUMMARY")
print("=" * 60)

display(
    diagnostic_df["route_score"].describe()
)

CORRELATION WITH SUPPLIED ROUTE SCORE
============================================================

route_score                 1.000000
route_safety_score          0.524599
water_depth_m               0.253451
eez_boundary_distance_km    0.235001
route_score_calculated      0.156871
mpa_distance_km             0.096192
distance_km                 0.072004
travel_time_hr              0.072004
fuel_l_proxy                0.072004
efficiency_score           -0.071879
current_speed_ms           -0.362516
geofence_caution           -0.455030
inside_mpa                       NaN
mpa_caution                      NaN
Name: route_score, dtype: float64

ROUTE SCORE BY CONSTRAINT
============================================================

Inside MPA:

            count      mean      min       max
inside_mpa
0            1542  0.946924  0.50891  0.999116
1               0       NaN      NaN       NaN

MPA caution:

             count      mean      min       max
mpa_caution
0             1542  0.946924  0.50891  0.999116
1                0       NaN      NaN       NaN

Geofence caution:

                  count      mean       min       max
geofence_caution
0                  1503  0.951324  0.508910  0.999116
1                    39  0.777349  0.511041  0.847719

ROUTE SCORE SUMMARY
============================================================

count    1542.000000
mean        0.946924
std         0.060050
min         0.508910
25%         0.939034
50%         0.964494
75%         0.979920
max         0.999116
Name: route_score, dtype: float64

In [ ]:
# ============================================================
# STEP 19: IMPROVED ROUTE EFFICIENCY SCORE
# ============================================================

# Distance, travel time and fuel are perfectly correlated
# in this dataset, so they represent one efficiency dimension.

distance_rank = (
    route_features_df["distance_km"]
    .rank(method="average", pct=True)
)

route_features_df["efficiency_score_v2"] = (
    1 - distance_rank
)

# Keep the score within 0-1
route_features_df["efficiency_score_v2"] = (
    route_features_df["efficiency_score_v2"]
    .clip(0, 1)
)


# ------------------------------------------------------------
# Inspect
# ------------------------------------------------------------

print("✅ Improved efficiency score calculated")

print("\nEfficiency score statistics:")
display(
    route_features_df[
        "efficiency_score_v2"
    ].describe()
)

print("\nUnique efficiency scores:")
print(
    route_features_df[
        "efficiency_score_v2"
    ].nunique()
)

print("\nSample:")
display(
    route_features_df[
        [
            "zone_id",
            "distance_km",
            "travel_time_hr",
            "fuel_l_proxy",
            "efficiency_score_v2"
        ]
    ].head(20)
)

✅ Improved efficiency score calculated

Efficiency score statistics:

count    2037.000000
mean        0.499755
std         0.288746
min         0.000000
25%         0.249877
50%         0.499755
75%         0.749632
max         0.999509
Name: efficiency_score_v2, dtype: float64

Unique efficiency scores:
1779

Sample:

    zone_id  distance_km  travel_time_hr  fuel_l_proxy  efficiency_score_v2
0   PFZ0001         20.0        1.111111      8.888889             0.961217
1   PFZ0002         16.0        0.888889      7.111111             0.979872
2   PFZ0003          8.0        0.444444      3.555556             0.990673
3   PFZ0004         27.0        1.500000     12.000000             0.930781
4   PFZ0005         33.0        1.833333     14.666667             0.900589
5   PFZ0006         34.0        1.888889     15.111111             0.895189
6   PFZ0007         29.0        1.611111     12.888889             0.921699
7   PFZ0008         30.0        1.666667     13.333333             0.918262
8   PFZ0009         27.0        1.500000     12.000000             0.930781
9   PFZ0010         45.0        2.500000     20.000000             0.838243
10  PFZ0011         33.0        1.833333     14.666667             0.900589
11  PFZ0012         18.0        1.000000      8.000000             0.971527
12  PFZ0013         27.0        1.500000     12.000000             0.930781
13  PFZ0014         13.0        0.722222      5.777778             0.985272
14  PFZ0015         17.0        0.944444      7.555556             0.976190
15  PFZ0016         20.0        1.111111      8.888889             0.961217
16  PFZ0017         17.0        0.944444      7.555556             0.976190
17  PFZ0018         20.0        1.111111      8.888889             0.961217
18  PFZ0019         22.0        1.222222      9.777778             0.953608
19  PFZ0020         26.0        1.444444     11.555556             0.937653

In [ ]:
# ============================================================
# STEP 20: CORRECTED FINAL ROUTE SCORE
# ============================================================

# ------------------------------------------------------------
# Independent Route Score components
#
# Route efficiency  = 50%
# Route safety      = 50%
#
# Distance, travel time and fuel are perfectly correlated
# in this dataset, so they are represented by ONE efficiency
# component instead of being counted three times.
# ------------------------------------------------------------

final_route_weights = {
    "efficiency_score_v2": 0.50,
    "route_safety_score": 0.50
}


def calculate_final_route_score(row):
    """
    Calculate final Route Score from independent components.

    Missing components are excluded and the remaining
    weights are re-normalized.
    """

    available = []

    for feature, weight in final_route_weights.items():

        if pd.notna(row[feature]):
            available.append(
                (row[feature], weight)
            )

    # No usable routing component
    if len(available) == 0:
        return np.nan

    total_weight = sum(
        weight for score, weight in available
    )

    score = sum(
        score * weight
        for score, weight in available
    ) / total_weight

    return np.clip(score, 0, 1)


# ------------------------------------------------------------
# Calculate final Route Score
# ------------------------------------------------------------

route_features_df["final_route_score"] = (
    route_features_df.apply(
        calculate_final_route_score,
        axis=1
    )
)


# ------------------------------------------------------------
# Route Score confidence
# ------------------------------------------------------------

route_features_df["final_route_confidence"] = (
    route_features_df[
        [
            "efficiency_score_v2",
            "route_safety_score"
        ]
    ]
    .notna()
    .sum(axis=1)
    / 2
)


# ------------------------------------------------------------
# Confidence-adjusted score
# ------------------------------------------------------------

route_features_df["adjusted_final_route_score"] = (
    route_features_df["final_route_score"]
    * route_features_df["final_route_confidence"]
)


# ------------------------------------------------------------
# Inspect
# ------------------------------------------------------------

print("✅ Corrected final Route Score calculated")

print("\nFinal Route Score statistics:")
display(
    route_features_df[
        "final_route_score"
    ].describe()
)

print("\nFinal Route Confidence:")
print(
    route_features_df[
        "final_route_confidence"
    ].value_counts(dropna=False)
)

print("\nSample:")
display(
    route_features_df[
        [
            "zone_id",
            "distance_km",
            "travel_time_hr",
            "fuel_l_proxy",
            "efficiency_score_v2",
            "route_safety_score",
            "final_route_score",
            "final_route_confidence",
            "adjusted_final_route_score"
        ]
    ].head(20)
)

✅ Corrected final Route Score calculated

Final Route Score statistics:

count    2037.000000
mean        0.602201
std         0.160255
min         0.198515
25%         0.482450
50%         0.610579
75%         0.727348
max         0.997054
Name: final_route_score, dtype: float64

Final Route Confidence:
final_route_confidence
1.0    2037
Name: count, dtype: int64

Sample:

,zone_id,distance_km,travel_time_hr,fuel_l_proxy,efficiency_score_v2,route_safety_score,final_route_score,final_route_confidence,adjusted_final_route_score
0,PFZ0001,20.0,1.111111,8.888889,0.961217,0.507893,0.734555,1.0,0.734555
1,PFZ0002,16.0,0.888889,7.111111,0.979872,0.540253,0.760062,1.0,0.760062
2,PFZ0003,8.0,0.444444,3.555556,0.990673,0.529597,0.760135,1.0,0.760135
3,PFZ0004,27.0,1.500000,12.000000,0.930781,0.598264,0.764522,1.0,0.764522
4,PFZ0005,33.0,1.833333,14.666667,0.900589,0.590766,0.745677,1.0,0.745677
5,PFZ0006,34.0,1.888889,15.111111,0.895189,0.761830,0.828510,1.0,0.828510
6,PFZ0007,29.0,1.611111,12.888889,0.921699,0.773932,0.847815,1.0,0.847815
7,PFZ0008,30.0,1.666667,13.333333,0.918262,0.765776,0.842019,1.0,0.842019
8,PFZ0009,27.0,1.500000,12.000000,0.930781,0.800767,0.865774,1.0,0.865774
9,PFZ0010,45.0,2.500000,20.000000,0.838243,0.928035,0.883139,1.0,0.883139
10,PFZ0011,33.0,1.833333,14.666667,0.900589,0.906199,0.903394,1.0,0.903394
11,PFZ0012,18.0,1.000000,8.000000,0.971527,0.871208,0.921367,1.0,0.921367
12,PFZ0013,27.0,1.500000,12.000000,0.930781,0.956327,0.943554,1.0,0.943554
13,PFZ0014,13.0,0.722222,5.777778,0.985272,0.663956,0.824614,1.0,0.824614
14,PFZ0015,17.0,0.944444,7.555556,0.976190,0.716390,0.846290,1.0,0.846290
15,PFZ0016,20.0,1.111111,8.888889,0.961217,0.720783,0.841000,1.0,0.841000
16,PFZ0017,17.0,0.944444,7.555556,0.976190,0.764536,0.870363,1.0,0.870363
17,PFZ0018,20.0,1.111111,8.888889,0.961217,0.572393,0.766805,1.0,0.766805
18,PFZ0019,22.0,1.222222,9.777778,0.953608,0.838990,0.896299,1.0,0.896299
19,PFZ0020,26.0,1.444444,11.555556,0.937653,0.992107,0.964880,1.0,0.964880

In [ ]:
# ============================================================
# STEP 21: FINAL ROUTE SCORE VALIDATION + RANKING
# ============================================================

print("===== FINAL ROUTE SCORE VALIDATION =====")


# ------------------------------------------------------------
# 1. Score range
# ------------------------------------------------------------

print("\nRoute Score range:")
print(
    "Minimum:",
    route_features_df["final_route_score"].min()
)

print(
    "Maximum:",
    route_features_df["final_route_score"].max()
)


# ------------------------------------------------------------
# 2. Missing scores
# ------------------------------------------------------------

print("\nMissing Route Scores:")

print(
    route_features_df[
        "final_route_score"
    ].isna().sum()
)


# ------------------------------------------------------------
# 3. Score distribution
# ------------------------------------------------------------

print("\nRoute Score distribution:")

display(
    route_features_df[
        "final_route_score"
    ].describe()
)


# ------------------------------------------------------------
# 4. Confidence distribution
# ------------------------------------------------------------

print("\nRoute Confidence distribution:")

print(
    route_features_df[
        "final_route_confidence"
    ].value_counts(dropna=False)
)


# ------------------------------------------------------------
# 5. TOP 10 routes
# ------------------------------------------------------------

print("\nTOP 10 ROUTES")
print("=" * 60)

top_routes = (
    route_features_df[
        [
            "zone_id",
            "region",
            "distance_km",
            "travel_time_hr",
            "fuel_l_proxy",
            "route_safety_score",
            "final_route_score",
            "final_route_confidence",
            "adjusted_final_route_score"
        ]
    ]
    .dropna(subset=["final_route_score"])
    .sort_values(
        "adjusted_final_route_score",
        ascending=False
    )
    .head(10)
    .reset_index(drop=True)
)

top_routes["route_rank"] = (
    top_routes.index + 1
)

display(
    top_routes[
        [
            "route_rank",
            "zone_id",
            "region",
            "distance_km",
            "travel_time_hr",
            "fuel_l_proxy",
            "route_safety_score",
            "final_route_score",
            "final_route_confidence",
            "adjusted_final_route_score"
        ]
    ]
)


# ------------------------------------------------------------
# 6. BOTTOM 10 routes
# ------------------------------------------------------------

print("\nBOTTOM 10 ROUTES")
print("=" * 60)

bottom_routes = (
    route_features_df[
        [
            "zone_id",
            "region",
            "distance_km",
            "travel_time_hr",
            "fuel_l_proxy",
            "route_safety_score",
            "final_route_score",
            "final_route_confidence",
            "adjusted_final_route_score"
        ]
    ]
    .dropna(subset=["final_route_score"])
    .sort_values(
        "adjusted_final_route_score",
        ascending=True
    )
    .head(10)
    .reset_index(drop=True)
)

bottom_routes["route_rank"] = (
    bottom_routes.index + 1
)

display(
    bottom_routes[
        [
            "route_rank",
            "zone_id",
            "region",
            "distance_km",
            "travel_time_hr",
            "fuel_l_proxy",
            "route_safety_score",
            "final_route_score",
            "final_route_confidence",
            "adjusted_final_route_score"
        ]
    ]
)

===== FINAL ROUTE SCORE VALIDATION =====

Route Score range:
Minimum: 0.19851531203128853
Maximum: 0.9970544918998527

Missing Route Scores:
0

Route Score distribution:

count    2037.000000
mean        0.602201
std         0.160255
min         0.198515
25%         0.482450
50%         0.610579
75%         0.727348
max         0.997054
Name: final_route_score, dtype: float64

Route Confidence distribution:
final_route_confidence
1.0    2037
Name: count, dtype: int64

TOP 10 ROUTES
============================================================

,route_rank,zone_id,region,distance_km,travel_time_hr,fuel_l_proxy,route_safety_score,final_route_score,final_route_confidence,adjusted_final_route_score
0,1,GRID_0475,INDIAN_MARINE,5.812542,0.322919,2.583352,1.000000,0.997054,1.0,0.997054
1,2,GRID_1492,INDIAN_MARINE,18.106210,1.005901,8.047204,1.000000,0.984782,1.0,0.984782
2,3,PFZ0169,LAKSHADWEEP,21.000000,1.166667,9.333333,1.000000,0.978768,1.0,0.978768
3,4,GRID_0649,INDIAN_MARINE,21.000585,1.166699,9.333593,0.985251,0.970779,1.0,0.970779
4,5,PFZ0171,LAKSHADWEEP,27.000000,1.500000,12.000000,1.000000,0.965390,1.0,0.965390
5,6,PFZ0020,ANDAMAN,26.000000,1.444444,11.555556,0.992107,0.964880,1.0,0.964880
6,7,GRID_0890,INDIAN_MARINE,28.471657,1.581759,12.654070,1.000000,0.961954,1.0,0.961954
7,8,PFZ0168,LAKSHADWEEP,18.000000,1.000000,8.000000,0.939718,0.955622,1.0,0.955622
8,9,GRID_1071,INDIAN_MARINE,27.579773,1.532210,12.257677,0.979479,0.953412,1.0,0.953412
9,10,GRID_0208,INDIAN_MARINE,31.429393,1.746077,13.968619,0.982369,0.946020,1.0,0.946020

BOTTOM 10 ROUTES
============================================================

,route_rank,zone_id,region,distance_km,travel_time_hr,fuel_l_proxy,route_safety_score,final_route_score,final_route_confidence,adjusted_final_route_score
0,1,GRID_0800,INDIAN_MARINE,487.893118,27.105173,216.841386,0.382794,0.198515,1.0,0.198515
1,2,GRID_0436,INDIAN_MARINE,445.399046,24.744391,197.955131,0.337280,0.204231,1.0,0.204231
2,3,GRID_0371,INDIAN_MARINE,431.575033,23.976391,191.811126,0.347540,0.220898,1.0,0.220898
3,4,GRID_0429,INDIAN_MARINE,413.907303,22.994850,183.958801,0.333333,0.230241,1.0,0.230241
4,5,GRID_0807,INDIAN_MARINE,495.112384,27.506244,220.049949,0.464088,0.235481,1.0,0.235481
5,6,GRID_1037,INDIAN_MARINE,407.375094,22.631950,181.055597,0.338069,0.238990,1.0,0.238990
6,7,GRID_0535,INDIAN_MARINE,471.250605,26.180589,209.444713,0.465404,0.250130,1.0,0.250130
7,8,GRID_0072,INDIAN_MARINE,498.709674,27.706093,221.648744,0.500000,0.250491,1.0,0.250491
8,9,GRID_0779,INDIAN_MARINE,496.126101,27.562561,220.500490,0.500000,0.252700,1.0,0.252700
9,10,GRID_0339,INDIAN_MARINE,495.476787,27.526488,220.211905,0.500000,0.253191,1.0,0.253191

In [ ]:
# ============================================================
# STEP 22: CORRECT FINAL ROUTE CONFIDENCE
# ============================================================

# Core routing information
core_route_features = [
    "distance_km",
    "travel_time_hr",
    "fuel_l_proxy",
    "water_depth_m",
    "current_speed_ms"
]

# ------------------------------------------------------------
# Count available core routing features
# ------------------------------------------------------------

route_features_df["route_core_available"] = (
    route_features_df[core_route_features]
    .notna()
    .sum(axis=1)
)

# ------------------------------------------------------------
# Data completeness
# ------------------------------------------------------------

route_features_df["final_route_confidence"] = (
    route_features_df["route_core_available"]
    / len(core_route_features)
)

# ------------------------------------------------------------
# Confidence-adjusted Route Score
# ------------------------------------------------------------

route_features_df["adjusted_final_route_score"] = (
    route_features_df["final_route_score"]
    * route_features_df["final_route_confidence"]
)


# ------------------------------------------------------------
# Validation / inspection
# ------------------------------------------------------------

print("✅ Final Route Confidence corrected")

print("\nConfidence distribution:")
print(
    route_features_df[
        "final_route_confidence"
    ].value_counts(dropna=False)
    .sort_index()
)

print("\nConfidence statistics:")
display(
    route_features_df[
        "final_route_confidence"
    ].describe()
)

print("\nSample:")
display(
    route_features_df[
        [
            "zone_id",
            "distance_km",
            "travel_time_hr",
            "fuel_l_proxy",
            "water_depth_m",
            "current_speed_ms",
            "final_route_score",
            "final_route_confidence",
            "adjusted_final_route_score"
        ]
    ].head(20)
)

✅ Final Route Confidence corrected

Confidence distribution:
final_route_confidence
0.8     495
1.0    1542
Name: count, dtype: int64

Confidence statistics:

count    2037.000000
mean        0.951399
std         0.085801
min         0.800000
25%         1.000000
50%         1.000000
75%         1.000000
max         1.000000
Name: final_route_confidence, dtype: float64

Sample:

,zone_id,distance_km,travel_time_hr,fuel_l_proxy,water_depth_m,current_speed_ms,final_route_score,final_route_confidence,adjusted_final_route_score
0,PFZ0001,20.0,1.111111,8.888889,20.0,NaN,0.734555,0.8,0.587644
1,PFZ0002,16.0,0.888889,7.111111,102.0,NaN,0.760062,0.8,0.608050
2,PFZ0003,8.0,0.444444,3.555556,75.0,NaN,0.760135,0.8,0.608108
3,PFZ0004,27.0,1.500000,12.000000,249.0,NaN,0.764522,0.8,0.611618
4,PFZ0005,33.0,1.833333,14.666667,230.0,NaN,0.745677,0.8,0.596542
5,PFZ0006,34.0,1.888889,15.111111,453.0,0.058917,0.828510,1.0,0.828510
6,PFZ0007,29.0,1.611111,12.888889,499.0,0.058917,0.847815,1.0,0.847815
7,PFZ0008,30.0,1.666667,13.333333,468.0,0.058917,0.842019,1.0,0.842019
8,PFZ0009,27.0,1.500000,12.000000,601.0,0.058917,0.865774,1.0,0.865774
9,PFZ0010,45.0,2.500000,20.000000,1149.0,0.070516,0.883139,1.0,0.883139
10,PFZ0011,33.0,1.833333,14.666667,1066.0,0.070516,0.903394,1.0,0.903394
11,PFZ0012,18.0,1.000000,8.000000,933.0,0.070516,0.921367,1.0,0.921367
12,PFZ0013,27.0,1.500000,12.000000,1101.0,0.031906,0.943554,1.0,0.943554
13,PFZ0014,13.0,0.722222,5.777778,38.0,0.051159,0.824614,1.0,0.824614
14,PFZ0015,17.0,0.944444,7.555556,189.0,0.041773,0.846290,1.0,0.846290
15,PFZ0016,20.0,1.111111,8.888889,254.0,0.051159,0.841000,1.0,0.841000
16,PFZ0017,17.0,0.944444,7.555556,372.0,0.040265,0.870363,1.0,0.870363
17,PFZ0018,20.0,1.111111,8.888889,64.0,0.009124,0.766805,1.0,0.766805
18,PFZ0019,22.0,1.222222,9.777778,655.0,0.040265,0.896299,1.0,0.896299
19,PFZ0020,26.0,1.444444,11.555556,1237.0,0.040265,0.964880,1.0,0.964880

In [ ]:
# ============================================================
# STEP 23: FINAL ROUTE AGENT JSON OUTPUT
# ============================================================

def get_route_conditions(zone_id):
    """
    Return structured JSON-compatible Route Agent output
    for a single zone.
    """

    # --------------------------------------------------------
    # Find zone
    # --------------------------------------------------------

    result = route_features_df[
        route_features_df["zone_id"]
        .astype(str)
        .str.upper()
        == str(zone_id).upper()
    ]

    # --------------------------------------------------------
    # Zone not found
    # --------------------------------------------------------

    if result.empty:
        return {
            "agent": "route_agent",
            "status": "error",
            "error": {
                "code": "zone_not_found",
                "message": f"Zone {zone_id} not found."
            }
        }

    row = result.iloc[0]

    # --------------------------------------------------------
    # Helper for safe numeric JSON values
    # --------------------------------------------------------

    def safe_float(value, decimals=4):
        if pd.isna(value):
            return None
        return round(float(value), decimals)

    # --------------------------------------------------------
    # Final structured response
    # --------------------------------------------------------

    return {
        "agent": "route_agent",
        "status": "success",

        "zone_id": row["zone_id"],

        "location": {
            "latitude": safe_float(row["latitude"]),
            "longitude": safe_float(row["longitude"])
        },

        "route_metrics": {
            "distance_km": safe_float(row["distance_km"]),
            "travel_time_hr": safe_float(row["travel_time_hr"]),
            "fuel_l": safe_float(row["fuel_l_proxy"])
        },

        "route_components": {
            "efficiency_score": safe_float(
                row["efficiency_score_v2"]
            ),
            "depth_safety_score": safe_float(
                row["depth_safety_score"]
            ),
            "constraint_safety_score": safe_float(
                row["constraint_safety_score"]
            ),
            "current_safety_score": safe_float(
                row["current_safety_score"]
            ),
            "route_safety_score": safe_float(
                row["route_safety_score"]
            )
        },

        "route_score": safe_float(
            row["final_route_score"]
        ),

        "confidence": safe_float(
            row["final_route_confidence"],
            decimals=2
        ),

        "adjusted_route_score": safe_float(
            row["adjusted_final_route_score"]
        ),

        "data_quality": {
            "features_available": int(
                row["route_core_available"]
            ),
            "features_total": 5,
            "completeness": safe_float(
                row["route_data_completeness"],
                decimals=2
            )
        }
    }


# ------------------------------------------------------------
# TEST
# ------------------------------------------------------------

test_zone = route_features_df["zone_id"].iloc[0]

route_json = get_route_conditions(
    test_zone
)

print(
    json.dumps(
        route_json,
        indent=2
    )
)

{
  "agent": "route_agent",
  "status": "success",
  "zone_id": "PFZ0001",
  "location": {
    "latitude": 13.1703,
    "longitude": 92.6403
  },
  "route_metrics": {
    "distance_km": 20.0,
    "travel_time_hr": 1.1111,
    "fuel_l": 8.8889
  },
  "route_components": {
    "efficiency_score": 0.9612,
    "depth_safety_score": 0.0158,
    "constraint_safety_score": 1.0,
    "current_safety_score": null,
    "route_safety_score": 0.5079
  },
  "route_score": 0.7346,
  "confidence": 0.8,
  "adjusted_route_score": 0.5876,
  "data_quality": {
    "features_available": 4,
    "features_total": 5,
    "completeness": 0.8
  }
}

In [ ]:
# ============================================================
# STEP 24: ROUTE AGENT QUERY INTERFACE
# ============================================================

def route_agent_query(
    query_type,
    zone_id=None,
    available_fuel_l=None,
    top_k=5
):
    """
    Common structured interface for the Route Agent.

    Supported query types:
    - zone
    - distance
    - time
    - fuel
    - shortest
    - closest
    - safest
    - lowest_fuel
    - fastest
    - fuel_feasibility
    - route
    """

    query_type = str(query_type).lower().strip()

    supported_queries = [
        "zone",
        "distance",
        "time",
        "fuel",
        "shortest",
        "closest",
        "safest",
        "lowest_fuel",
        "fastest",
        "fuel_feasibility",
        "route"
    ]

    # --------------------------------------------------------
    # Validate query type
    # --------------------------------------------------------

    if query_type not in supported_queries:
        return {
            "agent": "route_agent",
            "status": "error",
            "error": {
                "code": "unsupported_query_type",
                "message": (
                    "Supported query types: "
                    + ", ".join(supported_queries)
                )
            }
        }

    # --------------------------------------------------------
    # Single-zone query
    # --------------------------------------------------------

    if query_type in [
        "zone",
        "distance",
        "time",
        "fuel",
        "safest",
        "route"
    ]:

        if zone_id is None:
            return {
                "agent": "route_agent",
                "status": "error",
                "error": {
                    "code": "missing_zone_id",
                    "message": (
                        "zone_id is required "
                        "for this query."
                    )
                }
            }

        result = get_route_conditions(zone_id)

        if result.get("status") == "error":
            return result

        # Specific metric response
        if query_type == "distance":
            result = {
                "agent": "route_agent",
                "status": "success",
                "zone_id": result["zone_id"],
                "distance_km": (
                    result["route_metrics"]["distance_km"]
                )
            }

        elif query_type == "time":
            result = {
                "agent": "route_agent",
                "status": "success",
                "zone_id": result["zone_id"],
                "travel_time_hr": (
                    result["route_metrics"]["travel_time_hr"]
                )
            }

        elif query_type == "fuel":
            result = {
                "agent": "route_agent",
                "status": "success",
                "zone_id": result["zone_id"],
                "fuel_l": (
                    result["route_metrics"]["fuel_l"]
                )
            }

        return result

    # --------------------------------------------------------
    # Shortest / closest
    # --------------------------------------------------------

    if query_type in ["shortest", "closest"]:

        data = route_features_df.dropna(
            subset=["distance_km"]
        ).copy()

        row = data.loc[
            data["distance_km"].idxmin()
        ]

        return {
            "agent": "route_agent",
            "status": "success",
            "query": {
                "type": query_type
            },
            "result": {
                "zone_id": row["zone_id"],
                "distance_km": round(
                    float(row["distance_km"]),
                    4
                )
            }
        }

    # --------------------------------------------------------
    # Fastest
    # --------------------------------------------------------

    if query_type == "fastest":

        data = route_features_df.dropna(
            subset=["travel_time_hr"]
        ).copy()

        row = data.loc[
            data["travel_time_hr"].idxmin()
        ]

        return {
            "agent": "route_agent",
            "status": "success",
            "query": {
                "type": "fastest"
            },
            "result": {
                "zone_id": row["zone_id"],
                "travel_time_hr": round(
                    float(row["travel_time_hr"]),
                    4
                )
            }
        }

    # --------------------------------------------------------
    # Lowest fuel
    # --------------------------------------------------------

    if query_type == "lowest_fuel":

        data = route_features_df.dropna(
            subset=["fuel_l_proxy"]
        ).copy()

        row = data.loc[
            data["fuel_l_proxy"].idxmin()
        ]

        return {
            "agent": "route_agent",
            "status": "success",
            "query": {
                "type": "lowest_fuel"
            },
            "result": {
                "zone_id": row["zone_id"],
                "fuel_l": round(
                    float(row["fuel_l_proxy"]),
                    4
                )
            }
        }

    # --------------------------------------------------------
    # Fuel feasibility
    # --------------------------------------------------------

    if query_type == "fuel_feasibility":

        if zone_id is None:
            return {
                "agent": "route_agent",
                "status": "error",
                "error": {
                    "code": "missing_zone_id",
                    "message": (
                        "zone_id is required "
                        "for fuel feasibility."
                    )
                }
            }

        if available_fuel_l is None:
            return {
                "agent": "route_agent",
                "status": "error",
                "error": {
                    "code": "missing_fuel",
                    "message": (
                        "available_fuel_l is required."
                    )
                }
            }

        row = route_features_df[
            route_features_df["zone_id"] == zone_id
        ]

        if row.empty:
            return {
                "agent": "route_agent",
                "status": "error",
                "error": {
                    "code": "zone_not_found",
                    "message": (
                        f"Zone {zone_id} not found."
                    )
                }
            }

        row = row.iloc[0]

        required_fuel = row["fuel_l_proxy"]

        if pd.isna(required_fuel):
            return {
                "agent": "route_agent",
                "status": "error",
                "error": {
                    "code": "fuel_unavailable",
                    "message": (
                        "Fuel requirement unavailable."
                    )
                }
            }

        required_fuel = float(required_fuel)

        return {
            "agent": "route_agent",
            "status": "success",
            "query": {
                "type": "fuel_feasibility",
                "zone_id": zone_id,
                "available_fuel_l": float(
                    available_fuel_l
                )
            },
            "result": {
                "zone_id": zone_id,
                "required_fuel_l": round(
                    required_fuel,
                    4
                ),
                "available_fuel_l": round(
                    float(available_fuel_l),
                    4
                ),
                "reachable": (
                    float(available_fuel_l)
                    >= required_fuel
                )
            }
        }

    return {
        "agent": "route_agent",
        "status": "error",
        "error": {
            "code": "unhandled_query",
            "message": "Query could not be processed."
        }
    }


print("✅ Route Agent query interface created")

✅ Route Agent query interface created

In [ ]:
# ============================================================
# STEP 25: ROUTE AGENT PARAMETER VALIDATION
# ============================================================

def validate_route_request(request):
    """
    Validate a structured Route Agent request.

    Returns:
        {
            "valid": True
        }
        or
        {
            "valid": False,
            "error": {...}
        }
    """

    # --------------------------------------------------------
    # 1. Request must be a dictionary
    # --------------------------------------------------------

    if not isinstance(request, dict):
        return {
            "valid": False,
            "error": {
                "code": "invalid_request",
                "message": "Request must be a JSON object."
            }
        }

    # --------------------------------------------------------
    # 2. query_type required
    # --------------------------------------------------------

    query_type = request.get("query_type")

    supported = [
        "zone",
        "distance",
        "time",
        "fuel",
        "shortest",
        "closest",
        "safest",
        "lowest_fuel",
        "fastest",
        "fuel_feasibility",
        "route"
    ]

    if query_type is None:
        return {
            "valid": False,
            "error": {
                "code": "missing_query_type",
                "message": "query_type is required."
            },
            "supported_query_types": supported
        }

    query_type = str(query_type).lower().strip()

    # --------------------------------------------------------
    # 3. Supported query type
    # --------------------------------------------------------

    if query_type not in supported:
        return {
            "valid": False,
            "error": {
                "code": "unsupported_query_type",
                "message": (
                    f"Unsupported query type: {query_type}"
                )
            },
            "supported_query_types": supported
        }

    # --------------------------------------------------------
    # 4. Zone-dependent queries
    # --------------------------------------------------------

    zone_queries = [
        "zone",
        "distance",
        "time",
        "fuel",
        "safest",
        "route",
        "fuel_feasibility"
    ]

    if query_type in zone_queries:

        if not request.get("zone_id"):
            return {
                "valid": False,
                "error": {
                    "code": "missing_zone_id",
                    "message": (
                        "zone_id is required for "
                        f"{query_type} query."
                    )
                }
            }

    # --------------------------------------------------------
    # 5. Fuel feasibility validation
    # --------------------------------------------------------

    if query_type == "fuel_feasibility":

        fuel = request.get("available_fuel_l")

        if fuel is None:
            return {
                "valid": False,
                "error": {
                    "code": "missing_available_fuel",
                    "message": (
                        "available_fuel_l is required "
                        "for fuel feasibility query."
                    )
                }
            }

        if isinstance(fuel, bool):
            return {
                "valid": False,
                "error": {
                    "code": "invalid_available_fuel",
                    "message": (
                        "available_fuel_l must be numeric."
                    )
                }
            }

        try:
            fuel = float(fuel)
        except (TypeError, ValueError):
            return {
                "valid": False,
                "error": {
                    "code": "invalid_available_fuel",
                    "message": (
                        "available_fuel_l must be numeric."
                    )
                }
            }

        if fuel < 0:
            return {
                "valid": False,
                "error": {
                    "code": "invalid_available_fuel",
                    "message": (
                        "available_fuel_l cannot be negative."
                    )
                }
            }

    # --------------------------------------------------------
    # 6. Valid request
    # --------------------------------------------------------

    return {
        "valid": True
    }


print("✅ Route Agent parameter validation created")

✅ Route Agent parameter validation created

In [ ]:
# ============================================================
# STEP 25A: TEST ROUTE AGENT PARAMETER VALIDATION
# ============================================================

validation_tests = [
    {
        "name": "VALID_ZONE",
        "request": {
            "query_type": "zone",
            "zone_id": "PFZ0001"
        }
    },
    {
        "name": "MISSING_QUERY_TYPE",
        "request": {}
    },
    {
        "name": "MISSING_ZONE_ID",
        "request": {
            "query_type": "zone"
        }
    },
    {
        "name": "INVALID_QUERY_TYPE",
        "request": {
            "query_type": "something_else"
        }
    },
    {
        "name": "FUEL_WITHOUT_LIMIT",
        "request": {
            "query_type": "fuel_feasibility",
            "zone_id": "PFZ0001"
        }
    },
    {
        "name": "NEGATIVE_FUEL",
        "request": {
            "query_type": "fuel_feasibility",
            "zone_id": "PFZ0001",
            "available_fuel_l": -10
        }
    },
    {
        "name": "VALID_FUEL_CHECK",
        "request": {
            "query_type": "fuel_feasibility",
            "zone_id": "PFZ0001",
            "available_fuel_l": 20
        }
    }
]


for test in validation_tests:

    result = validate_route_request(
        test["request"]
    )

    print("\n" + "=" * 70)
    print(test["name"])
    print("=" * 70)

    print(
        json.dumps(
            result,
            indent=2
        )
    )

======================================================================
VALID_ZONE
======================================================================
{
  "valid": true
}

======================================================================
MISSING_QUERY_TYPE
======================================================================
{
  "valid": false,
  "error": {
    "code": "missing_query_type",
    "message": "query_type is required."
  },
  "supported_query_types": [
    "zone",
    "distance",
    "time",
    "fuel",
    "shortest",
    "closest",
    "safest",
    "lowest_fuel",
    "fastest",
    "fuel_feasibility",
    "route"
  ]
}

======================================================================
MISSING_ZONE_ID
======================================================================
{
  "valid": false,
  "error": {
    "code": "missing_zone_id",
    "message": "zone_id is required for zone query."
  }
}

======================================================================
INVALID_QUERY_TYPE
======================================================================
{
  "valid": false,
  "error": {
    "code": "unsupported_query_type",
    "message": "Unsupported query type: something_else"
  },
  "supported_query_types": [
    "zone",
    "distance",
    "time",
    "fuel",
    "shortest",
    "closest",
    "safest",
    "lowest_fuel",
    "fastest",
    "fuel_feasibility",
    "route"
  ]
}

======================================================================
FUEL_WITHOUT_LIMIT
======================================================================
{
  "valid": false,
  "error": {
    "code": "missing_available_fuel",
    "message": "available_fuel_l is required for fuel feasibility query."
  }
}

======================================================================
NEGATIVE_FUEL
======================================================================
{
  "valid": false,
  "error": {
    "code": "invalid_available_fuel",
    "message": "available_fuel_l cannot be negative."
  }
}

======================================================================
VALID_FUEL_CHECK
======================================================================
{
  "valid": true
}

In [ ]:
# ============================================================
# STEP 26: FINAL VALIDATED ROUTE AGENT WRAPPER
# ============================================================

def run_route_agent(request):
    """
    Final structured Route Agent interface.

    Request:
        JSON-compatible dictionary

    Response:
        JSON-compatible Route Agent response
    """

    # --------------------------------------------------------
    # 1. Validate request
    # --------------------------------------------------------

    validation = validate_route_request(request)

    if not validation["valid"]:
        return {
            "agent": "route_agent",
            "status": "error",
            "error": validation["error"],
            **(
                {
                    "supported_query_types":
                    validation["supported_query_types"]
                }
                if "supported_query_types" in validation
                else {}
            )
        }

    # --------------------------------------------------------
    # 2. Normalize query type
    # --------------------------------------------------------

    query_type = (
        str(request["query_type"])
        .lower()
        .strip()
    )

    # --------------------------------------------------------
    # 3. Execute Route Agent query
    # --------------------------------------------------------

    response = route_agent_query(
        query_type=query_type,
        zone_id=request.get("zone_id"),
        available_fuel_l=request.get(
            "available_fuel_l"
        ),
        top_k=request.get("top_k", 5)
    )

    # --------------------------------------------------------
    # 4. Return structured response
    # --------------------------------------------------------

    return response


print("✅ Validated Route Agent wrapper created")

✅ Validated Route Agent wrapper created

In [ ]:
# ============================================================
# STEP 26A: TEST VALIDATED ROUTE AGENT
# ============================================================

test_request = {
    "query_type": "zone",
    "zone_id": "PFZ0001"
}

response = run_route_agent(test_request)

print(
    json.dumps(
        response,
        indent=2,
        default=str
    )
)

{
  "agent": "route_agent",
  "status": "success",
  "zone_id": "PFZ0001",
  "location": {
    "latitude": 13.1703,
    "longitude": 92.6403
  },
  "route_metrics": {
    "distance_km": 20.0,
    "travel_time_hr": 1.1111,
    "fuel_l": 8.8889
  },
  "route_components": {
    "efficiency_score": 0.9612,
    "depth_safety_score": 0.0158,
    "constraint_safety_score": 1.0,
    "current_safety_score": null,
    "route_safety_score": 0.5079
  },
  "route_score": 0.7346,
  "confidence": 0.8,
  "adjusted_route_score": 0.5876,
  "data_quality": {
    "features_available": 4,
    "features_total": 5,
    "completeness": 0.8
  }
}

In [ ]:
# ============================================================
# STEP 27: NATURAL-LANGUAGE ROUTE QUERY PARSER
# ============================================================

import re


def parse_route_query(query):
    """
    Convert a natural-language routing query into
    a structured Route Agent request.
    """

    # --------------------------------------------------------
    # 1. Validate query
    # --------------------------------------------------------

    if not isinstance(query, str) or not query.strip():
        return {
            "status": "error",
            "error": "invalid_query",
            "message": "Query must be a non-empty string."
        }

    q = query.lower().strip()

    # --------------------------------------------------------
    # 2. Detect zone ID
    # --------------------------------------------------------

    zone_match = re.search(
        r"\b(?:pfz|grid)\d+\b",
        q,
        re.IGNORECASE
    )

    detected_zone = (
        zone_match.group(0).upper()
        if zone_match
        else None
    )

    # --------------------------------------------------------
    # 3. Detect fuel value
    # --------------------------------------------------------

    fuel_match = re.search(
        r"(\d+(?:\.\d+)?)\s*(?:litres?|liters?|l)\b",
        q,
        re.IGNORECASE
    )

    detected_fuel = (
        float(fuel_match.group(1))
        if fuel_match
        else None
    )

    # --------------------------------------------------------
    # 4. Determine query type
    # --------------------------------------------------------

    # Fuel feasibility
    if (
        ("reach" in q or "reaching" in q)
        and ("fuel" in q)
    ):
        query_type = "fuel_feasibility"

    # Shortest / closest
    elif (
        "shortest route" in q
        or "shortest" in q
    ):
        query_type = "shortest"

    elif (
        "closest" in q
        or "nearest" in q
    ):
        query_type = "closest"

    # Lowest fuel
    elif (
        "least fuel" in q
        or "lowest fuel" in q
        or "minimum fuel" in q
        or "min fuel" in q
    ):
        query_type = "lowest_fuel"

    # Travel time
    elif (
        "travel time" in q
        or "how long" in q
        or "time" in q
    ):
        query_type = "time"

    # Distance
    elif (
        "how far" in q
        or "distance" in q
        or "far" in q
    ):
        query_type = "distance"

    # Safest route
    elif (
        "safest route" in q
        or "safest" in q
        or "safe route" in q
    ):
        query_type = "safest"

    # Fastest route
    elif (
        "fastest route" in q
        or "lowest travel time" in q
        or "quickest route" in q
    ):
        query_type = "fastest"

    # Fuel requirement
    elif (
        "fuel" in q
        and (
            "need" in q
            or "require" in q
            or "required" in q
        )
    ):
        query_type = "fuel"

    # General route request
    elif "route" in q:
        query_type = "route"

    else:
        return {
            "status": "error",
            "error": "unsupported_query",
            "message": (
                "Could not determine the routing query type."
            )
        }

    # --------------------------------------------------------
    # 5. Build structured request
    # --------------------------------------------------------

    request = {
        "query_type": query_type
    }

    if detected_zone is not None:
        request["zone_id"] = detected_zone

    if detected_fuel is not None:
        request["available_fuel_l"] = detected_fuel

    return {
        "status": "success",
        **request
    }


print("✅ Natural-language Route Query Parser created")

✅ Natural-language Route Query Parser created

In [ ]:
# ============================================================
# STEP 27A: TEST ROUTE QUERY PARSER
# ============================================================

test_queries = [
    "What is the shortest route to PFZ0001?",
    "How far is PFZ0001 from my harbour?",
    "How long will it take to reach PFZ0001?",
    "How much fuel will I need to reach PFZ0001?",
    "Which fishing zone requires the least fuel?",
    "Which zone is closest to my current location?",
    "What is the safest route to PFZ0001?",
    "Which route has the lowest travel time?",
    "Can I reach PFZ0001 with 20 litres of fuel?",
    "Show me the route from my harbour to PFZ0001."
]


for i, query in enumerate(test_queries, 1):

    parsed = parse_route_query(query)

    print("\n" + "=" * 75)
    print(f"TEST {i}")
    print("QUERY:", query)
    print("PARSED REQUEST:")

    print(
        json.dumps(
            parsed,
            indent=2
        )
    )

===========================================================================
TEST 1
QUERY: What is the shortest route to PFZ0001?
PARSED REQUEST:
{
  "status": "success",
  "query_type": "shortest",
  "zone_id": "PFZ0001"
}

===========================================================================
TEST 2
QUERY: How far is PFZ0001 from my harbour?
PARSED REQUEST:
{
  "status": "success",
  "query_type": "distance",
  "zone_id": "PFZ0001"
}

===========================================================================
TEST 3
QUERY: How long will it take to reach PFZ0001?
PARSED REQUEST:
{
  "status": "success",
  "query_type": "time",
  "zone_id": "PFZ0001"
}

===========================================================================
TEST 4
QUERY: How much fuel will I need to reach PFZ0001?
PARSED REQUEST:
{
  "status": "success",
  "query_type": "fuel_feasibility",
  "zone_id": "PFZ0001"
}

===========================================================================
TEST 5
QUERY: Which fishing zone requires the least fuel?
PARSED REQUEST:
{
  "status": "success",
  "query_type": "lowest_fuel"
}

===========================================================================
TEST 6
QUERY: Which zone is closest to my current location?
PARSED REQUEST:
{
  "status": "success",
  "query_type": "closest"
}

===========================================================================
TEST 7
QUERY: What is the safest route to PFZ0001?
PARSED REQUEST:
{
  "status": "success",
  "query_type": "safest",
  "zone_id": "PFZ0001"
}

===========================================================================
TEST 8
QUERY: Which route has the lowest travel time?
PARSED REQUEST:
{
  "status": "success",
  "query_type": "time"
}

===========================================================================
TEST 9
QUERY: Can I reach PFZ0001 with 20 litres of fuel?
PARSED REQUEST:
{
  "status": "success",
  "query_type": "fuel_feasibility",
  "zone_id": "PFZ0001",
  "available_fuel_l": 20.0
}

===========================================================================
TEST 10
QUERY: Show me the route from my harbour to PFZ0001.
PARSED REQUEST:
{
  "status": "success",
  "query_type": "route",
  "zone_id": "PFZ0001"
}

In [ ]:
# ============================================================
# STEP 28: NATURAL LANGUAGE ROUTE AGENT
# ============================================================

def ask_route_agent(query):
    """
    Final natural-language Route Agent interface.

    Flow:
        Natural language
            ↓
        Query parser
            ↓
        Request validation
            ↓
        Route Agent
            ↓
        Structured JSON
    """

    # --------------------------------------------------------
    # 1. Parse natural-language query
    # --------------------------------------------------------

    parsed_request = parse_route_query(query)

    if parsed_request.get("status") != "success":
        error_response = {
            "agent": "route_agent",
            "status": "error",
            "error": {
                "code": parsed_request.get(
                    "error",
                    "query_parse_error"
                ),
                "message": parsed_request.get(
                    "message",
                    "Could not understand the routing query."
                )
            }
        }

        return {
            "answer": error_response["error"]["message"],
            "data": error_response
        }

    # --------------------------------------------------------
    # 2. Remove parser-only status field
    # --------------------------------------------------------

    agent_request = {
        key: value
        for key, value in parsed_request.items()
        if key != "status"
    }

    # --------------------------------------------------------
    # 3. Run validated Route Agent
    # --------------------------------------------------------

    response = run_route_agent(agent_request)

    # --------------------------------------------------------
    # 4. Generate simple human-readable answer
    # --------------------------------------------------------

    if response.get("status") == "success":

        query_type = agent_request.get(
            "query_type"
        )

        if query_type == "distance":
            answer = (
                f"Distance to {response['zone_id']} is "
                f"{response['distance_km']} km."
            )

        elif query_type == "time":
            answer = (
                f"Travel time to {response['zone_id']} is "
                f"{response['travel_time_hr']} hours."
            )

        elif query_type == "fuel":
            answer = (
                f"Estimated fuel requirement for "
                f"{response['zone_id']} is "
                f"{response['fuel_l']} litres."
            )

        elif query_type == "fuel_feasibility":
            result = response.get("result", {})

            answer = (
                f"{result.get('zone_id')} is "
                f"{'reachable' if result.get('reachable') else 'not reachable'} "
                f"with {result.get('available_fuel_l')} litres of fuel."
            )

        elif query_type in [
            "shortest",
            "closest",
            "fastest",
            "lowest_fuel"
        ]:
            result = response.get("result", {})

            answer = (
                f"Best matching zone is "
                f"{result.get('zone_id')}."
            )

        elif query_type == "safest":
            result = response.get("result", {})

            answer = (
                f"The highest-scoring route is "
                f"{result.get('zone_id')} with a "
                f"route score of {result.get('route_score')}."
            )

        else:
            answer = (
                f"Route information generated successfully "
                f"for {response.get('zone_id')}."
            )

    else:
        answer = response.get(
            "error",
            {}).get(
                "message",
                "Route Agent could not process the query."
            )

    # --------------------------------------------------------
    # 5. Return answer + machine-readable data
    # --------------------------------------------------------

    return {
        "answer": answer,
        "data": response
    }


print("✅ Final natural-language Route Agent created")

✅ Final natural-language Route Agent created

In [ ]:
# ============================================================
# STEP 28A: FINAL NATURAL LANGUAGE ROUTE TESTS
# ============================================================

test_queries = [
    "What is the shortest route to PFZ0001?",
    "How far is PFZ0001 from my harbour?",
    "How long will it take to reach PFZ0001?",
    "How much fuel will I need to reach PFZ0001?",
    "Which fishing zone requires the least fuel?",
    "Which zone is closest to my current location?",
    "What is the safest route to PFZ0001?",
    "Which route has the lowest travel time?",
    "Can I reach PFZ0001 with 20 litres of fuel?",
    "Show me the route from my harbour to PFZ0001."
]


for i, query in enumerate(test_queries, 1):

    result = ask_route_agent(query)

    print("\n" + "=" * 80)
    print(f"TEST {i}")
    print("=" * 80)

    print("USER QUERY:")
    print(query)

    print("\nANSWER:")
    print(result["answer"])

    print("\nJSON DATA:")
    print(
        json.dumps(
            result["data"],
            indent=2,
            default=str
        )
    )

================================================================================
TEST 1
================================================================================
USER QUERY:
What is the shortest route to PFZ0001?

ANSWER:
Best matching zone is GRID_0757.

JSON DATA:
{
  "agent": "route_agent",
  "status": "success",
  "query": {
    "type": "shortest"
  },
  "result": {
    "zone_id": "GRID_0757",
    "distance_km": 1.4555
  }
}

================================================================================
TEST 2
================================================================================
USER QUERY:
How far is PFZ0001 from my harbour?

ANSWER:
Distance to PFZ0001 is 20.0 km.

JSON DATA:
{
  "agent": "route_agent",
  "status": "success",
  "zone_id": "PFZ0001",
  "distance_km": 20.0
}

================================================================================
TEST 3
================================================================================
USER QUERY:
How long will it take to reach PFZ0001?

ANSWER:
Travel time to PFZ0001 is 1.1111 hours.

JSON DATA:
{
  "agent": "route_agent",
  "status": "success",
  "zone_id": "PFZ0001",
  "travel_time_hr": 1.1111
}

================================================================================
TEST 4
================================================================================
USER QUERY:
How much fuel will I need to reach PFZ0001?

ANSWER:
available_fuel_l is required for fuel feasibility query.

JSON DATA:
{
  "agent": "route_agent",
  "status": "error",
  "error": {
    "code": "missing_available_fuel",
    "message": "available_fuel_l is required for fuel feasibility query."
  }
}

================================================================================
TEST 5
================================================================================
USER QUERY:
Which fishing zone requires the least fuel?

ANSWER:
Best matching zone is GRID_0757.

JSON DATA:
{
  "agent": "route_agent",
  "status": "success",
  "query": {
    "type": "lowest_fuel"
  },
  "result": {
    "zone_id": "GRID_0757",
    "fuel_l": 0.6469
  }
}

================================================================================
TEST 6
================================================================================
USER QUERY:
Which zone is closest to my current location?

ANSWER:
Best matching zone is GRID_0757.

JSON DATA:
{
  "agent": "route_agent",
  "status": "success",
  "query": {
    "type": "closest"
  },
  "result": {
    "zone_id": "GRID_0757",
    "distance_km": 1.4555
  }
}

================================================================================
TEST 7
================================================================================
USER QUERY:
What is the safest route to PFZ0001?

ANSWER:
The highest-scoring route is None with a route score of None.

JSON DATA:
{
  "agent": "route_agent",
  "status": "success",
  "zone_id": "PFZ0001",
  "location": {
    "latitude": 13.1703,
    "longitude": 92.6403
  },
  "route_metrics": {
    "distance_km": 20.0,
    "travel_time_hr": 1.1111,
    "fuel_l": 8.8889
  },
  "route_components": {
    "efficiency_score": 0.9612,
    "depth_safety_score": 0.0158,
    "constraint_safety_score": 1.0,
    "current_safety_score": null,
    "route_safety_score": 0.5079
  },
  "route_score": 0.7346,
  "confidence": 0.8,
  "adjusted_route_score": 0.5876,
  "data_quality": {
    "features_available": 4,
    "features_total": 5,
    "completeness": 0.8
  }
}

================================================================================
TEST 8
================================================================================
USER QUERY:
Which route has the lowest travel time?

ANSWER:
zone_id is required for time query.

JSON DATA:
{
  "agent": "route_agent",
  "status": "error",
  "error": {
    "code": "missing_zone_id",
    "message": "zone_id is required for time query."
  }
}

================================================================================
TEST 9
================================================================================
USER QUERY:
Can I reach PFZ0001 with 20 litres of fuel?

ANSWER:
PFZ0001 is reachable with 20.0 litres of fuel.

JSON DATA:
{
  "agent": "route_agent",
  "status": "success",
  "query": {
    "type": "fuel_feasibility",
    "zone_id": "PFZ0001",
    "available_fuel_l": 20.0
  },
  "result": {
    "zone_id": "PFZ0001",
    "required_fuel_l": 8.8889,
    "available_fuel_l": 20.0,
    "reachable": true
  }
}

================================================================================
TEST 10
================================================================================
USER QUERY:
Show me the route from my harbour to PFZ0001.

ANSWER:
Route information generated successfully for PFZ0001.

JSON DATA:
{
  "agent": "route_agent",
  "status": "success",
  "zone_id": "PFZ0001",
  "location": {
    "latitude": 13.1703,
    "longitude": 92.6403
  },
  "route_metrics": {
    "distance_km": 20.0,
    "travel_time_hr": 1.1111,
    "fuel_l": 8.8889
  },
  "route_components": {
    "efficiency_score": 0.9612,
    "depth_safety_score": 0.0158,
    "constraint_safety_score": 1.0,
    "current_safety_score": null,
    "route_safety_score": 0.5079
  },
  "route_score": 0.7346,
  "confidence": 0.8,
  "adjusted_route_score": 0.5876,
  "data_quality": {
    "features_available": 4,
    "features_total": 5,
    "completeness": 0.8
  }
}

In [ ]:
# ============================================================
# STEP 29: CORRECTED NATURAL-LANGUAGE ROUTE QUERY PARSER
# ============================================================

def parse_route_query(query):
    """
    Convert a natural-language routing query into
    a structured Route Agent request.
    """

    # --------------------------------------------------------
    # 1. Validate query
    # --------------------------------------------------------

    if not isinstance(query, str) or not query.strip():
        return {
            "status": "error",
            "error": "invalid_query",
            "message": "Query must be a non-empty string."
        }

    q = query.lower().strip()

    # --------------------------------------------------------
    # 2. Detect zone ID
    # --------------------------------------------------------

    zone_match = re.search(
        r"\b(?:pfz|grid)\d+\b",
        q,
        re.IGNORECASE
    )

    detected_zone = (
        zone_match.group(0).upper()
        if zone_match
        else None
    )

    # --------------------------------------------------------
    # 3. Detect fuel quantity
    # --------------------------------------------------------

    fuel_match = re.search(
        r"(\d+(?:\.\d+)?)\s*(?:litres?|liters?|l)\b",
        q,
        re.IGNORECASE
    )

    detected_fuel = (
        float(fuel_match.group(1))
        if fuel_match
        else None
    )

    # --------------------------------------------------------
    # 4. Determine query type
    # --------------------------------------------------------

    # IMPORTANT:
    # More specific intents are checked first.

    # Fuel feasibility
    if (
        ("reach" in q or "reaching" in q)
        and "fuel" in q
    ):
        query_type = "fuel_feasibility"

    # Safest route
    elif (
        "safest route" in q
        or "safest" in q
        or "safe route" in q
    ):
        query_type = "safest"

    # Fastest / lowest travel time
    elif (
        "fastest route" in q
        or "lowest travel time" in q
        or "quickest route" in q
        or "fastest" in q
    ):
        query_type = "fastest"

    # Shortest route
    elif (
        "shortest route" in q
        or "shortest" in q
    ):
        query_type = "shortest"

    # Closest / nearest
    elif (
        "closest" in q
        or "nearest" in q
    ):
        query_type = "closest"

    # Lowest fuel
    elif (
        "least fuel" in q
        or "lowest fuel" in q
        or "minimum fuel" in q
        or "min fuel" in q
    ):
        query_type = "lowest_fuel"

    # Travel time
    elif (
        "how long" in q
        or "travel time" in q
    ):
        query_type = "time"

    # Distance
    elif (
        "how far" in q
        or "distance" in q
    ):
        query_type = "distance"

    # Fuel requirement
    elif (
        "how much fuel" in q
        or "fuel will i need" in q
        or "fuel required" in q
        or "fuel requirement" in q
    ):
        query_type = "fuel"

    # General route request
    elif "route" in q:
        query_type = "route"

    else:
        return {
            "status": "error",
            "error": "unsupported_query",
            "message": (
                "Could not determine the routing query type."
            )
        }

    # --------------------------------------------------------
    # 5. Build structured request
    # --------------------------------------------------------

    request = {
        "query_type": query_type
    }

    if detected_zone is not None:
        request["zone_id"] = detected_zone

    if detected_fuel is not None:
        request["available_fuel_l"] = detected_fuel

    return {
        "status": "success",
        **request
    }


print("✅ Corrected Route Query Parser loaded")

✅ Corrected Route Query Parser loaded

In [ ]:
# ============================================================
# STEP 29A: ROUTE PARSER VALIDATION
# ============================================================

parser_tests = [
    "What is the shortest route to PFZ0001?",
    "How far is PFZ0001 from my harbour?",
    "How long will it take to reach PFZ0001?",
    "How much fuel will I need to reach PFZ0001?",
    "Which fishing zone requires the least fuel?",
    "Which zone is closest to my current location?",
    "What is the safest route to PFZ0001?",
    "Which route has the lowest travel time?",
    "Can I reach PFZ0001 with 20 litres of fuel?",
    "Show me the route from my harbour to PFZ0001."
]

for i, query in enumerate(parser_tests, 1):

    parsed = parse_route_query(query)

    print("\n" + "=" * 80)
    print(f"TEST {i}")
    print("QUERY:", query)

    print("\nPARSED JSON:")
    print(
        json.dumps(
            parsed,
            indent=2
        )
    )

================================================================================
TEST 1
QUERY: What is the shortest route to PFZ0001?

PARSED JSON:
{
  "status": "success",
  "query_type": "shortest",
  "zone_id": "PFZ0001"
}

================================================================================
TEST 2
QUERY: How far is PFZ0001 from my harbour?

PARSED JSON:
{
  "status": "success",
  "query_type": "distance",
  "zone_id": "PFZ0001"
}

================================================================================
TEST 3
QUERY: How long will it take to reach PFZ0001?

PARSED JSON:
{
  "status": "success",
  "query_type": "time",
  "zone_id": "PFZ0001"
}

================================================================================
TEST 4
QUERY: How much fuel will I need to reach PFZ0001?

PARSED JSON:
{
  "status": "success",
  "query_type": "fuel_feasibility",
  "zone_id": "PFZ0001"
}

================================================================================
TEST 5
QUERY: Which fishing zone requires the least fuel?

PARSED JSON:
{
  "status": "success",
  "query_type": "lowest_fuel"
}

================================================================================
TEST 6
QUERY: Which zone is closest to my current location?

PARSED JSON:
{
  "status": "success",
  "query_type": "closest"
}

================================================================================
TEST 7
QUERY: What is the safest route to PFZ0001?

PARSED JSON:
{
  "status": "success",
  "query_type": "safest",
  "zone_id": "PFZ0001"
}

================================================================================
TEST 8
QUERY: Which route has the lowest travel time?

PARSED JSON:
{
  "status": "success",
  "query_type": "fastest"
}

================================================================================
TEST 9
QUERY: Can I reach PFZ0001 with 20 litres of fuel?

PARSED JSON:
{
  "status": "success",
  "query_type": "fuel_feasibility",
  "zone_id": "PFZ0001",
  "available_fuel_l": 20.0
}

================================================================================
TEST 10
QUERY: Show me the route from my harbour to PFZ0001.

PARSED JSON:
{
  "status": "success",
  "query_type": "route",
  "zone_id": "PFZ0001"
}

In [ ]:
# ============================================================
# STEP 30: FINAL END-TO-END ROUTE AGENT TEST
# ============================================================

final_queries = [
    "What is the shortest route to PFZ0001?",
    "How far is PFZ0001 from my harbour?",
    "How long will it take to reach PFZ0001?",
    "How much fuel will I need to reach PFZ0001?",
    "Which fishing zone requires the least fuel?",
    "Which zone is closest to my current location?",
    "What is the safest route to PFZ0001?",
    "Which route has the lowest travel time?",
    "Can I reach PFZ0001 with 20 litres of fuel?",
    "Show me the route from my harbour to PFZ0001."
]

for i, query in enumerate(final_queries, 1):

    result = ask_route_agent(query)

    print("\n" + "=" * 90)
    print(f"TEST {i}")
    print("=" * 90)

    print("QUERY:")
    print(query)

    print("\nANSWER:")
    print(result.get("answer"))

    print("\nJSON:")
    print(
        json.dumps(
            result.get("data"),
            indent=2,
            default=str
        )
    )

==========================================================================================
TEST 1
==========================================================================================
QUERY:
What is the shortest route to PFZ0001?

ANSWER:
Best matching zone is GRID_0757.

JSON:
{
  "agent": "route_agent",
  "status": "success",
  "query": {
    "type": "shortest"
  },
  "result": {
    "zone_id": "GRID_0757",
    "distance_km": 1.4555
  }
}

==========================================================================================
TEST 2
==========================================================================================
QUERY:
How far is PFZ0001 from my harbour?

ANSWER:
Distance to PFZ0001 is 20.0 km.

JSON:
{
  "agent": "route_agent",
  "status": "success",
  "zone_id": "PFZ0001",
  "distance_km": 20.0
}

==========================================================================================
TEST 3
==========================================================================================
QUERY:
How long will it take to reach PFZ0001?

ANSWER:
Travel time to PFZ0001 is 1.1111 hours.

JSON:
{
  "agent": "route_agent",
  "status": "success",
  "zone_id": "PFZ0001",
  "travel_time_hr": 1.1111
}

==========================================================================================
TEST 4
==========================================================================================
QUERY:
How much fuel will I need to reach PFZ0001?

ANSWER:
available_fuel_l is required for fuel feasibility query.

JSON:
{
  "agent": "route_agent",
  "status": "error",
  "error": {
    "code": "missing_available_fuel",
    "message": "available_fuel_l is required for fuel feasibility query."
  }
}

==========================================================================================
TEST 5
==========================================================================================
QUERY:
Which fishing zone requires the least fuel?

ANSWER:
Best matching zone is GRID_0757.

JSON:
{
  "agent": "route_agent",
  "status": "success",
  "query": {
    "type": "lowest_fuel"
  },
  "result": {
    "zone_id": "GRID_0757",
    "fuel_l": 0.6469
  }
}

==========================================================================================
TEST 6
==========================================================================================
QUERY:
Which zone is closest to my current location?

ANSWER:
Best matching zone is GRID_0757.

JSON:
{
  "agent": "route_agent",
  "status": "success",
  "query": {
    "type": "closest"
  },
  "result": {
    "zone_id": "GRID_0757",
    "distance_km": 1.4555
  }
}

==========================================================================================
TEST 7
==========================================================================================
QUERY:
What is the safest route to PFZ0001?

ANSWER:
The highest-scoring route is None with a route score of None.

JSON:
{
  "agent": "route_agent",
  "status": "success",
  "zone_id": "PFZ0001",
  "location": {
    "latitude": 13.1703,
    "longitude": 92.6403
  },
  "route_metrics": {
    "distance_km": 20.0,
    "travel_time_hr": 1.1111,
    "fuel_l": 8.8889
  },
  "route_components": {
    "efficiency_score": 0.9612,
    "depth_safety_score": 0.0158,
    "constraint_safety_score": 1.0,
    "current_safety_score": null,
    "route_safety_score": 0.5079
  },
  "route_score": 0.7346,
  "confidence": 0.8,
  "adjusted_route_score": 0.5876,
  "data_quality": {
    "features_available": 4,
    "features_total": 5,
    "completeness": 0.8
  }
}

==========================================================================================
TEST 8
==========================================================================================
QUERY:
Which route has the lowest travel time?

ANSWER:
Best matching zone is GRID_0757.

JSON:
{
  "agent": "route_agent",
  "status": "success",
  "query": {
    "type": "fastest"
  },
  "result": {
    "zone_id": "GRID_0757",
    "travel_time_hr": 0.0809
  }
}

==========================================================================================
TEST 9
==========================================================================================
QUERY:
Can I reach PFZ0001 with 20 litres of fuel?

ANSWER:
PFZ0001 is reachable with 20.0 litres of fuel.

JSON:
{
  "agent": "route_agent",
  "status": "success",
  "query": {
    "type": "fuel_feasibility",
    "zone_id": "PFZ0001",
    "available_fuel_l": 20.0
  },
  "result": {
    "zone_id": "PFZ0001",
    "required_fuel_l": 8.8889,
    "available_fuel_l": 20.0,
    "reachable": true
  }
}

==========================================================================================
TEST 10
==========================================================================================
QUERY:
Show me the route from my harbour to PFZ0001.

ANSWER:
Route information generated successfully for PFZ0001.

JSON:
{
  "agent": "route_agent",
  "status": "success",
  "zone_id": "PFZ0001",
  "location": {
    "latitude": 13.1703,
    "longitude": 92.6403
  },
  "route_metrics": {
    "distance_km": 20.0,
    "travel_time_hr": 1.1111,
    "fuel_l": 8.8889
  },
  "route_components": {
    "efficiency_score": 0.9612,
    "depth_safety_score": 0.0158,
    "constraint_safety_score": 1.0,
    "current_safety_score": null,
    "route_safety_score": 0.5079
  },
  "route_score": 0.7346,
  "confidence": 0.8,
  "adjusted_route_score": 0.5876,
  "data_quality": {
    "features_available": 4,
    "features_total": 5,
    "completeness": 0.8
  }
}

In [ ]:
# ============================================================
# STEP 31: M3 FINAL VALIDATION SUITE
# ============================================================

def validate_route_agent():

    tests = [
        {
            "name": "Zone Query",
            "request": {
                "query_type": "zone",
                "zone_id": "PFZ0001"
            }
        },
        {
            "name": "Distance Query",
            "request": {
                "query_type": "distance",
                "zone_id": "PFZ0001"
            }
        },
        {
            "name": "Time Query",
            "request": {
                "query_type": "time",
                "zone_id": "PFZ0001"
            }
        },
        {
            "name": "Fuel Query",
            "request": {
                "query_type": "fuel",
                "zone_id": "PFZ0001"
            }
        },
        {
            "name": "Shortest Route",
            "request": {
                "query_type": "shortest"
            }
        },
        {
            "name": "Closest Zone",
            "request": {
                "query_type": "closest"
            }
        },
        {
            "name": "Fastest Route",
            "request": {
                "query_type": "fastest"
            }
        },
        {
            "name": "Lowest Fuel",
            "request": {
                "query_type": "lowest_fuel"
            }
        },
        {
            "name": "Safest Route",
            "request": {
                "query_type": "safest",
                "zone_id": "PFZ0001"
            }
        },
        {
            "name": "Fuel Feasibility",
            "request": {
                "query_type": "fuel_feasibility",
                "zone_id": "PFZ0001",
                "available_fuel_l": 20
            }
        }
    ]

    results = []

    for test in tests:

        try:
            response = run_route_agent(
                test["request"]
            )

            passed = (
                isinstance(response, dict)
                and response.get("agent") == "route_agent"
                and response.get("status") in [
                    "success",
                    "error"
                ]
            )

            results.append({
                "test": test["name"],
                "status": "PASS" if passed else "FAIL",
                "agent_status": response.get("status")
            })

        except Exception as e:

            results.append({
                "test": test["name"],
                "status": "FAIL",
                "agent_status": str(e)
            })

    return results


validation_results = validate_route_agent()

print("M3 ROUTE AGENT VALIDATION")
print("=" * 70)

for r in validation_results:
    print(
        f"{r['status']:4} | "
        f"{r['test']:25} | "
        f"status={r['agent_status']}"
    )

M3 ROUTE AGENT VALIDATION
======================================================================
PASS | Zone Query                | status=success
PASS | Distance Query            | status=success
PASS | Time Query                | status=success
PASS | Fuel Query                | status=success
PASS | Shortest Route            | status=success
PASS | Closest Zone              | status=success
PASS | Fastest Route             | status=success
PASS | Lowest Fuel               | status=success
PASS | Safest Route              | status=success
PASS | Fuel Feasibility          | status=success

In [ ]:
# ============================================================
# STEP 32: SAVE FINAL M3 ROUTING DATA
# ============================================================

final_route_columns = [
    "zone_id",
    "region",
    "latitude",
    "longitude",

    # Raw route metrics
    "distance_km",
    "travel_time_hr",
    "fuel_l_proxy",

    # Raw safety information
    "water_depth_m",
    "current_u_ms",
    "current_v_ms",
    "current_speed_ms",
    "inside_mpa",
    "mpa_caution",
    "geofence_caution",
    "mpa_distance_km",
    "eez_boundary_distance_km",

    # Calculated components
    "efficiency_score_v2",
    "depth_safety_score",
    "constraint_safety_score",
    "current_safety_score",
    "route_safety_score",

    # Final M3 outputs
    "final_route_score",
    "final_route_confidence",
    "adjusted_final_route_score"
]

final_route_df = route_features_df[
    final_route_columns
].copy()

output_path = "M3_final_routing_dataset.csv"

final_route_df.to_csv(
    output_path,
    index=False
)

print("✅ Final M3 routing dataset saved:")
print(output_path)

print("\nShape:", final_route_df.shape)

display(
    final_route_df.head(10)
)

✅ Final M3 routing dataset saved:
M3_final_routing_dataset.csv

Shape: (2037, 24)

,zone_id,region,latitude,longitude,distance_km,travel_time_hr,fuel_l_proxy,water_depth_m,current_u_ms,current_v_ms,...,mpa_distance_km,eez_boundary_distance_km,efficiency_score_v2,depth_safety_score,constraint_safety_score,current_safety_score,route_safety_score,final_route_score,final_route_confidence,adjusted_final_route_score
0,PFZ0001,ANDAMAN,13.170278,92.640278,20.0,1.111111,8.888889,20.0,NaN,NaN,...,1053.068365,7.999635,0.961217,0.015785,1.0,NaN,0.507893,0.734555,0.8,0.587644
1,PFZ0002,ANDAMAN,11.760000,92.946944,16.0,0.888889,7.111111,102.0,NaN,NaN,...,1213.398008,66.300979,0.979872,0.080505,1.0,NaN,0.540253,0.760062,0.8,0.608050
2,PFZ0003,ANDAMAN,11.745000,93.004444,8.0,0.444444,3.555556,75.0,NaN,NaN,...,1215.136296,72.801917,0.990673,0.059195,1.0,NaN,0.529597,0.760135,0.8,0.608108
3,PFZ0004,ANDAMAN,11.694444,93.021944,27.0,1.500000,12.000000,249.0,NaN,NaN,...,1220.900345,77.071736,0.930781,0.196527,1.0,NaN,0.598264,0.764522,0.8,0.611618
4,PFZ0005,ANDAMAN,11.632500,93.021111,33.0,1.833333,14.666667,230.0,NaN,NaN,...,1227.940194,80.073879,0.900589,0.181531,1.0,NaN,0.590766,0.745677,0.8,0.596542
5,PFZ0006,ANDAMAN,11.587778,93.025833,34.0,1.888889,15.111111,453.0,-0.0295,0.0510,...,1233.027342,82.773633,0.895189,0.357537,1.0,0.927953,0.761830,0.828510,1.0,0.828510
6,PFZ0007,ANDAMAN,11.563889,92.999444,29.0,1.611111,12.888889,499.0,-0.0295,0.0510,...,1235.717176,81.322685,0.921699,0.393844,1.0,0.927953,0.773932,0.847815,1.0,0.847815
7,PFZ0008,ANDAMAN,11.535556,92.975556,30.0,1.666667,13.333333,468.0,-0.0295,0.0510,...,1238.920167,80.343072,0.918262,0.369376,1.0,0.927953,0.765776,0.842019,1.0,0.842019
8,PFZ0009,ANDAMAN,11.501944,92.983889,27.0,1.500000,12.000000,601.0,-0.0295,0.0510,...,1242.743572,82.850260,0.930781,0.474349,1.0,0.927953,0.800767,0.865774,1.0,0.865774
9,PFZ0010,ANDAMAN,11.362500,92.978333,45.0,2.500000,20.000000,1149.0,-0.0435,0.0555,...,1258.577063,86.413956,0.838243,0.906867,1.0,0.877238,0.928035,0.883139,1.0,0.883139

In [ ]:
# ============================================================
# STEP 34: SAVE FINAL M3 ROUTE ENGINE ARTIFACT
# ============================================================

import joblib

route_model_artifact = {
    "artifact_type": "deterministic_route_scoring_engine",
    "version": "M3_v2",

    # Efficiency reference
    "efficiency": {
        "method": "empirical_percentile_rank",
        "direction": "lower_distance_is_better"
    },

    # Safety references
    "safety_references": {
        "depth_q10": float(depth_q10),
        "depth_q50": float(depth_q50),
        "depth_q90": float(depth_q90),

        "current_q10": float(current_safety_q10),
        "current_q50": float(current_safety_q50),
        "current_q90": float(current_safety_q90),

        "mpa_distance_q10": float(mpa_q10),
        "mpa_distance_q50": float(mpa_q50),
        "mpa_distance_q90": float(mpa_q90),

        "eez_distance_q10": float(eez_q10),
        "eez_distance_q50": float(eez_q50),
        "eez_distance_q90": float(eez_q90)
    },

    # Safety component weights
    "safety_weights": {
        "depth": 1 / 3,
        "constraints": 1 / 3,
        "current": 1 / 3
    },

    # Final route-score weights
    "route_score_weights": {
        "efficiency": 0.50,
        "safety": 0.50
    },


    # Required output contract
    "output_contract": {
        "agent": "route_agent",
        "score_field": "route_score",
        "metrics": [
            "distance_km",
            "travel_time_hr",
            "fuel_l"
        ],
        "confidence_field": "confidence"
    },

    # Critical methodological rule
    "reference_route_score_used_for_training": False
}

joblib.dump(
    route_model_artifact,
    "route_model.pkl"
)

print("✅ Final M3 route engine artifact saved")
print("File: route_model.pkl")

✅ Final M3 route engine artifact saved
File: route_model.pkl

In [ ]:
# ============================================================
# STEP 35: CREATE FINAL M3 predict.py
# ============================================================

predict_code = r'''
import os
import joblib
import pandas as pd
import numpy as np

MODEL_PATH = os.path.join(
    os.path.dirname(__file__),
    "route_model.pkl"
)

model_artifact = joblib.load(MODEL_PATH)


def safe_float(value, decimals=4):
    if pd.isna(value):
        return None
    return round(float(value), decimals)


def predict_route(row):
    """
    Generate the final structured Route Agent output.

    The supplied dataset route_score is NOT used
    for prediction.
    """

    efficiency = row.get("efficiency_score_v2")
    route_safety = row.get("route_safety_score")

    components = []

    if pd.notna(efficiency):
        components.append(
            (
                float(efficiency),
                model_artifact["route_score_weights"]["efficiency"]
            )
        )

    if pd.notna(route_safety):
        components.append(
            (
                float(route_safety),
                model_artifact["route_score_weights"]["safety"]
            )
        )

    if not components:
        return {
            "agent": "route_agent",
            "status": "error",
            "error": {
                "code": "insufficient_route_data",
                "message": "Insufficient routing information."
            }
        }

    total_weight = sum(
        weight for score, weight in components
    )

    route_score = sum(
        score * weight
        for score, weight in components
    ) / total_weight

    route_score = float(
        np.clip(route_score, 0, 1)
    )

    available = sum(
        pd.notna(row.get(feature))
        for feature in [
            "distance_km",
            "travel_time_hr",
            "fuel_l_proxy",
            "water_depth_m",
            "current_speed_ms"
        ]
    )

    confidence = available / 5.0

    return {
        "agent": "route_agent",
        "status": "success",

        "zone_id": str(row["zone_id"]),

        "location": {
            "latitude": safe_float(row.get("latitude")),
            "longitude": safe_float(row.get("longitude"))
        },

        "route_metrics": {
            "distance_km": safe_float(
                row.get("distance_km")
            ),
            "travel_time_hr": safe_float(
                row.get("travel_time_hr")
            ),
            "fuel_l": safe_float(
                row.get("fuel_l_proxy")
            )
        },

        "route_score": round(
            route_score,
            4
        ),

        "confidence": round(
            confidence,
            2
        ),

        "data_quality": {
            "features_available": int(available),
            "features_total": 5,
            "completeness": round(
                confidence,
                2
            )
        }
    }
'''

with open("predict.py", "w") as f:
    f.write(predict_code)

print("✅ predict.py created")

✅ predict.py created